In [12]:
import pandas as pd

In [14]:
df = pd.read_excel(r"C:\Users\Nandhana\Downloads\EMPLOYEE.xlsx")
df

,EmployeeID,Name,Age,Gender,Department,Salary,City,JoinDate,Performance,Email
0,1001,Rahul,22,Female,NaN,55000,Bangalore,NaN,good,test@mail.com
1,1002,Kiran,31,M,Marketing,NaN,Calicut,2023-01-15,NaN,invalidemail
2,1003,Anu,Thirty,F,Sales,"48,000",NaN,NaN,Good,test@mail.com
3,1004,John,27,F,Marketing,35000,Calicut,15/02/2022,good,user@example.com
4,1005,Aisha,25,NaN,IT,"48,000",NaN,15/02/2022,Good,NaN
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000,kochi,2024/03/01,good,NaN
96,1097,Mohammed,29,Male,HR,35000,NaN,15/02/2022,Excellent,invalidemail
97,1098,Anu,22,Male,HR,NaN,NaN,NaN,good,test@mail.com
98,1099,Arun,22,Female,IT,42000,Kochi,15/02/2022,NaN,invalidemail
99,1100,Sara,31,Female,IT,55000,NaN,2023-01-15,Poor,invalidemail

In [99]:
df.head(10)

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,Marketing,55000.0,Bangalore,Unknown,Good,Test@Mail.Com
1,1002,Kiran,31,Male,Marketing,48000.0,Calicut,2023-01-15,Unknown,Invalidemail
2,1003,Anu,30,Female,Sales,48000.0,Unknown,Unknown,Good,Test@Mail.Com
3,1004,John,27,Female,Marketing,35000.0,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,15/02/2022,Good,Unknown
5,1006,Deepa,27,Female,Hr,48000.0,Unknown,15/02/2022,Unknown,Unknown
6,1007,Priya,30,Unknown,Marketing,48000.0,Bangalore,2024/03/01,Unknown,Invalidemail
7,1008,Aisha,27,Unknown,Marketing,48000.0,Unknown,2023-01-15,Excellent,Invalidemail
8,1009,Mohammed,29,Male,Marketing,55000.0,Unknown,2023-01-15,Unknown,User@Example.Com
9,1010,Mohammed,25,Female,Hr,48000.0,Bangalore,Unknown,Unknown,Invalidemail

In [16]:
df.shape

(100, 10)

In [17]:
df.columns

Index(['EmployeeID', 'Name', 'Age', 'Gender', 'Department', 'Salary', 'City',
       'JoinDate', 'Performance', 'Email'],
      dtype='str')

In [18]:
df.dtypes

EmployeeID      int64
Name              str
Age            object
Gender            str
Department        str
Salary         object
City              str
JoinDate          str
Performance       str
Email             str
dtype: object

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   EmployeeID   100 non-null    int64
 1   Name         100 non-null    str
 2   Age          82 non-null     object
 3   Gender       75 non-null     str
 4   Department   85 non-null     str
 5   Salary       77 non-null     object
 6   City         70 non-null     str
 7   JoinDate     83 non-null     str
 8   Performance  81 non-null     str
 9   Email        75 non-null     str
dtypes: int64(1), object(2), str(7)
memory usage: 7.9+ KB

In [20]:
df.describe()

        EmployeeID
count   100.000000
mean   1050.400000
std      29.151988
min    1001.000000
25%    1025.750000
50%    1050.500000
75%    1075.250000
max    1100.000000

In [21]:
df.nunique()

EmployeeID     99
Name           18
Age             6
Gender          4
Department      6
Salary          4
City            5
JoinDate        3
Performance     4
Email           3
dtype: int64

In [100]:
df.isna().sum()

employeeid     0
name           0
age            0
gender         0
department     0
salary         0
city           0
joindate       0
performance    0
email          0
dtype: int64

In [24]:
df.duplicated().sum()

np.int64(0)

In [25]:
df["EmployeeID"].duplicated().sum()

np.int64(1)

In [26]:
df.columns=df.columns.str.lower()
df.columns

Index(['employeeid', 'name', 'age', 'gender', 'department', 'salary', 'city',
       'joindate', 'performance', 'email'],
      dtype='str')

In [27]:
df.columns.str.replace(" ","_",regex=False)
df.columns

Index(['employeeid', 'name', 'age', 'gender', 'department', 'salary', 'city',
       'joindate', 'performance', 'email'],
      dtype='str')

In [101]:
df["name"]=df["name"].str.title()
df["department"]=df["department"].str.title()
df["city"]=df["city"].str.title()
df["gender"]=df["gender"].str.title()
df["performance"]=df["performance"].str.title()
df["email"]=df["email"].str.title()
df

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,Marketing,55000.0,Bangalore,Unknown,Good,Test@Mail.Com
1,1002,Kiran,31,Male,Marketing,48000.0,Calicut,2023-01-15,Unknown,Invalidemail
2,1003,Anu,30,Female,Sales,48000.0,Unknown,Unknown,Good,Test@Mail.Com
3,1004,John,27,Female,Marketing,35000.0,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,15/02/2022,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024/03/01,Good,Unknown
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,Unknown,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15/02/2022,Unknown,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15,Poor,Invalidemail

In [102]:
df["age"].apply(type).value_counts()

age
<class 'int'>    99
Name: count, dtype: int64

In [103]:
df["age"] = df["age"].replace("Thirty", 30)
df

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,Marketing,55000.0,Bangalore,Unknown,Good,Test@Mail.Com
1,1002,Kiran,31,Male,Marketing,48000.0,Calicut,2023-01-15,Unknown,Invalidemail
2,1003,Anu,30,Female,Sales,48000.0,Unknown,Unknown,Good,Test@Mail.Com
3,1004,John,27,Female,Marketing,35000.0,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,15/02/2022,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024/03/01,Good,Unknown
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,Unknown,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15/02/2022,Unknown,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15,Poor,Invalidemail

In [104]:
df["age"] = df["age"].fillna(df["age"].median())
df

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,Marketing,55000.0,Bangalore,Unknown,Good,Test@Mail.Com
1,1002,Kiran,31,Male,Marketing,48000.0,Calicut,2023-01-15,Unknown,Invalidemail
2,1003,Anu,30,Female,Sales,48000.0,Unknown,Unknown,Good,Test@Mail.Com
3,1004,John,27,Female,Marketing,35000.0,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,15/02/2022,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024/03/01,Good,Unknown
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,Unknown,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15/02/2022,Unknown,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15,Poor,Invalidemail

In [105]:
df["age"] = df["age"].astype(int)
df

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,Marketing,55000.0,Bangalore,Unknown,Good,Test@Mail.Com
1,1002,Kiran,31,Male,Marketing,48000.0,Calicut,2023-01-15,Unknown,Invalidemail
2,1003,Anu,30,Female,Sales,48000.0,Unknown,Unknown,Good,Test@Mail.Com
3,1004,John,27,Female,Marketing,35000.0,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,15/02/2022,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024/03/01,Good,Unknown
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,Unknown,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15/02/2022,Unknown,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15,Poor,Invalidemail

In [41]:
df["age"].apply(type).value_counts()

age
<class 'int'>    100
Name: count, dtype: int64

In [49]:
df["age"] = df["age"].fillna(df["age"].mean())
df

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,NaN,55000,Bangalore,NaN,Good,Test@Mail.Com
1,1002,Kiran,31,M,Marketing,NaN,Calicut,2023-01-15,NaN,Invalidemail
2,1003,Anu,30,F,Sales,"48,000",NaN,NaN,Good,Test@Mail.Com
3,1004,John,27,F,Marketing,35000,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,NaN,It,"48,000",NaN,15/02/2022,Good,NaN
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000,Kochi,2024/03/01,Good,NaN
96,1097,Mohammed,29,Male,Hr,35000,NaN,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,NaN,NaN,NaN,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000,Kochi,15/02/2022,NaN,Invalidemail
99,1100,Sara,31,Female,It,55000,NaN,2023-01-15,Poor,Invalidemail

In [47]:
df["salary"].apply(type).value_counts()

salary
<class 'int'>      63
<class 'float'>    23
<class 'str'>      14
Name: count, dtype: int64

In [106]:
df["salary"] = df["salary"].replace(",", "", regex=True)
df

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,Marketing,55000.0,Bangalore,Unknown,Good,Test@Mail.Com
1,1002,Kiran,31,Male,Marketing,48000.0,Calicut,2023-01-15,Unknown,Invalidemail
2,1003,Anu,30,Female,Sales,48000.0,Unknown,Unknown,Good,Test@Mail.Com
3,1004,John,27,Female,Marketing,35000.0,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,15/02/2022,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024/03/01,Good,Unknown
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,Unknown,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15/02/2022,Unknown,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15,Poor,Invalidemail

In [107]:
df["salary"] = df["salary"].astype(float)
df

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,Marketing,55000.0,Bangalore,Unknown,Good,Test@Mail.Com
1,1002,Kiran,31,Male,Marketing,48000.0,Calicut,2023-01-15,Unknown,Invalidemail
2,1003,Anu,30,Female,Sales,48000.0,Unknown,Unknown,Good,Test@Mail.Com
3,1004,John,27,Female,Marketing,35000.0,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,15/02/2022,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024/03/01,Good,Unknown
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,Unknown,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15/02/2022,Unknown,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15,Poor,Invalidemail

In [108]:
df["salary"] = df["salary"].fillna(df["salary"].median())
df

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,Marketing,55000.0,Bangalore,Unknown,Good,Test@Mail.Com
1,1002,Kiran,31,Male,Marketing,48000.0,Calicut,2023-01-15,Unknown,Invalidemail
2,1003,Anu,30,Female,Sales,48000.0,Unknown,Unknown,Good,Test@Mail.Com
3,1004,John,27,Female,Marketing,35000.0,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,15/02/2022,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024/03/01,Good,Unknown
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,Unknown,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15/02/2022,Unknown,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15,Poor,Invalidemail

In [109]:
df["department"] = df["department"].fillna(df["department"].mode()[0])
df

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,Marketing,55000.0,Bangalore,Unknown,Good,Test@Mail.Com
1,1002,Kiran,31,Male,Marketing,48000.0,Calicut,2023-01-15,Unknown,Invalidemail
2,1003,Anu,30,Female,Sales,48000.0,Unknown,Unknown,Good,Test@Mail.Com
3,1004,John,27,Female,Marketing,35000.0,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,15/02/2022,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024/03/01,Good,Unknown
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,Unknown,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15/02/2022,Unknown,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15,Poor,Invalidemail

In [110]:
df["city"] = df["city"].fillna("Unknown")
df

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,Marketing,55000.0,Bangalore,Unknown,Good,Test@Mail.Com
1,1002,Kiran,31,Male,Marketing,48000.0,Calicut,2023-01-15,Unknown,Invalidemail
2,1003,Anu,30,Female,Sales,48000.0,Unknown,Unknown,Good,Test@Mail.Com
3,1004,John,27,Female,Marketing,35000.0,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,15/02/2022,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024/03/01,Good,Unknown
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,Unknown,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15/02/2022,Unknown,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15,Poor,Invalidemail

In [111]:
df["gender"] = df["gender"].fillna("Unknown")
df

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,Marketing,55000.0,Bangalore,Unknown,Good,Test@Mail.Com
1,1002,Kiran,31,Male,Marketing,48000.0,Calicut,2023-01-15,Unknown,Invalidemail
2,1003,Anu,30,Female,Sales,48000.0,Unknown,Unknown,Good,Test@Mail.Com
3,1004,John,27,Female,Marketing,35000.0,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,15/02/2022,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024/03/01,Good,Unknown
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,Unknown,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15/02/2022,Unknown,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15,Poor,Invalidemail

In [112]:
df["performance"] = df["performance"].fillna("Unknown")
df

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,Marketing,55000.0,Bangalore,Unknown,Good,Test@Mail.Com
1,1002,Kiran,31,Male,Marketing,48000.0,Calicut,2023-01-15,Unknown,Invalidemail
2,1003,Anu,30,Female,Sales,48000.0,Unknown,Unknown,Good,Test@Mail.Com
3,1004,John,27,Female,Marketing,35000.0,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,15/02/2022,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024/03/01,Good,Unknown
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,Unknown,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15/02/2022,Unknown,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15,Poor,Invalidemail

In [113]:
df["email"] = df["email"].fillna("Unknown")
df

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,Marketing,55000.0,Bangalore,Unknown,Good,Test@Mail.Com
1,1002,Kiran,31,Male,Marketing,48000.0,Calicut,2023-01-15,Unknown,Invalidemail
2,1003,Anu,30,Female,Sales,48000.0,Unknown,Unknown,Good,Test@Mail.Com
3,1004,John,27,Female,Marketing,35000.0,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,15/02/2022,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024/03/01,Good,Unknown
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,Unknown,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15/02/2022,Unknown,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15,Poor,Invalidemail

In [114]:
df["salary"] = pd.to_numeric(df["salary"])
df

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,Marketing,55000.0,Bangalore,Unknown,Good,Test@Mail.Com
1,1002,Kiran,31,Male,Marketing,48000.0,Calicut,2023-01-15,Unknown,Invalidemail
2,1003,Anu,30,Female,Sales,48000.0,Unknown,Unknown,Good,Test@Mail.Com
3,1004,John,27,Female,Marketing,35000.0,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,15/02/2022,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024/03/01,Good,Unknown
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,Unknown,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15/02/2022,Unknown,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15,Poor,Invalidemail

In [115]:

df["salary"] = df["salary"].replace("N/A", None)
df

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,Marketing,55000.0,Bangalore,Unknown,Good,Test@Mail.Com
1,1002,Kiran,31,Male,Marketing,48000.0,Calicut,2023-01-15,Unknown,Invalidemail
2,1003,Anu,30,Female,Sales,48000.0,Unknown,Unknown,Good,Test@Mail.Com
3,1004,John,27,Female,Marketing,35000.0,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,15/02/2022,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024/03/01,Good,Unknown
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,Unknown,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15/02/2022,Unknown,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15,Poor,Invalidemail

In [116]:
df["salary"].dtype

dtype('float64')

In [117]:
df["gender"] = df["gender"].replace({
    "M": "Male",
    "F": "Female"
})
df

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,Marketing,55000.0,Bangalore,Unknown,Good,Test@Mail.Com
1,1002,Kiran,31,Male,Marketing,48000.0,Calicut,2023-01-15,Unknown,Invalidemail
2,1003,Anu,30,Female,Sales,48000.0,Unknown,Unknown,Good,Test@Mail.Com
3,1004,John,27,Female,Marketing,35000.0,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,15/02/2022,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024/03/01,Good,Unknown
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,Unknown,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15/02/2022,Unknown,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15,Poor,Invalidemail

In [118]:
df["gender"] = df["gender"].fillna("Unknown")
df

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,Marketing,55000.0,Bangalore,Unknown,Good,Test@Mail.Com
1,1002,Kiran,31,Male,Marketing,48000.0,Calicut,2023-01-15,Unknown,Invalidemail
2,1003,Anu,30,Female,Sales,48000.0,Unknown,Unknown,Good,Test@Mail.Com
3,1004,John,27,Female,Marketing,35000.0,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,15/02/2022,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024/03/01,Good,Unknown
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,Unknown,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15/02/2022,Unknown,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15,Poor,Invalidemail

In [128]:
df["joindate"] = df["joindate"].str.replace("/""-",regex=False)
df

TypeError: repl must be a string or callable

In [120]:
df["city"] = df["city"].str.strip().str.title()
df

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,Marketing,55000.0,Bangalore,Unknown,Good,Test@Mail.Com
1,1002,Kiran,31,Male,Marketing,48000.0,Calicut,2023-01-15,Unknown,Invalidemail
2,1003,Anu,30,Female,Sales,48000.0,Unknown,Unknown,Good,Test@Mail.Com
3,1004,John,27,Female,Marketing,35000.0,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,15/02/2022,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024/03/01,Good,Unknown
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,Unknown,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15/02/2022,Unknown,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15,Poor,Invalidemail

In [121]:
df["city"] = df["city"].fillna("Unknown")
df

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,Marketing,55000.0,Bangalore,Unknown,Good,Test@Mail.Com
1,1002,Kiran,31,Male,Marketing,48000.0,Calicut,2023-01-15,Unknown,Invalidemail
2,1003,Anu,30,Female,Sales,48000.0,Unknown,Unknown,Good,Test@Mail.Com
3,1004,John,27,Female,Marketing,35000.0,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,15/02/2022,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024/03/01,Good,Unknown
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,Unknown,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15/02/2022,Unknown,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15,Poor,Invalidemail

In [122]:
df["department"] = df["department"].str.strip().str.title()
df

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,Marketing,55000.0,Bangalore,Unknown,Good,Test@Mail.Com
1,1002,Kiran,31,Male,Marketing,48000.0,Calicut,2023-01-15,Unknown,Invalidemail
2,1003,Anu,30,Female,Sales,48000.0,Unknown,Unknown,Good,Test@Mail.Com
3,1004,John,27,Female,Marketing,35000.0,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,15/02/2022,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024/03/01,Good,Unknown
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,Unknown,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15/02/2022,Unknown,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15,Poor,Invalidemail

In [123]:
df["department"] = df["department"].replace("", "Unknown")
df

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,Marketing,55000.0,Bangalore,Unknown,Good,Test@Mail.Com
1,1002,Kiran,31,Male,Marketing,48000.0,Calicut,2023-01-15,Unknown,Invalidemail
2,1003,Anu,30,Female,Sales,48000.0,Unknown,Unknown,Good,Test@Mail.Com
3,1004,John,27,Female,Marketing,35000.0,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,15/02/2022,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024/03/01,Good,Unknown
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,Unknown,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15/02/2022,Unknown,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15,Poor,Invalidemail

In [124]:
df["performance"] = df["performance"].str.strip().str.title()
df

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,Marketing,55000.0,Bangalore,Unknown,Good,Test@Mail.Com
1,1002,Kiran,31,Male,Marketing,48000.0,Calicut,2023-01-15,Unknown,Invalidemail
2,1003,Anu,30,Female,Sales,48000.0,Unknown,Unknown,Good,Test@Mail.Com
3,1004,John,27,Female,Marketing,35000.0,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,15/02/2022,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024/03/01,Good,Unknown
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,Unknown,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15/02/2022,Unknown,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15,Poor,Invalidemail

In [125]:
df["performance"] = df["performance"].fillna("Unknown")
df

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,Marketing,55000.0,Bangalore,Unknown,Good,Test@Mail.Com
1,1002,Kiran,31,Male,Marketing,48000.0,Calicut,2023-01-15,Unknown,Invalidemail
2,1003,Anu,30,Female,Sales,48000.0,Unknown,Unknown,Good,Test@Mail.Com
3,1004,John,27,Female,Marketing,35000.0,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,15/02/2022,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024/03/01,Good,Unknown
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,Unknown,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15/02/2022,Unknown,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15,Poor,Invalidemail

In [126]:
df["performance"].value_counts()

performance
Good         42
Excellent    20
Unknown      19
Poor         18
Name: count, dtype: int64

In [127]:
df = df.drop_duplicates(subset="employeeid", keep="first")
df

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,Marketing,55000.0,Bangalore,Unknown,Good,Test@Mail.Com
1,1002,Kiran,31,Male,Marketing,48000.0,Calicut,2023-01-15,Unknown,Invalidemail
2,1003,Anu,30,Female,Sales,48000.0,Unknown,Unknown,Good,Test@Mail.Com
3,1004,John,27,Female,Marketing,35000.0,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,15/02/2022,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024/03/01,Good,Unknown
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,Unknown,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15/02/2022,Unknown,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15,Poor,Invalidemail

In [86]:
df.shape

(99, 10)