In [1]:
import pandas as pd

In [81]:
df = pd.read_csv(r"C:\Users\Nandhana\Downloads\details.csv",header=None)
df

      0         1     2       3        4        5           6
0   101  Mohammed  24.0    Male  45000.0       IT  2023-01-15
1   102     Aisha  27.0  Female  52000.0       HR  2022-11-10
2   103     Rahul   NaN    Male  38000.0    Sales  2023-05-21
3   104     Priya  29.0  Female      NaN  Finance  2021-07-18
4   105      John  31.0    Male  60000.0       IT         NaN
5   106     Sneha  26.0  Female  47000.0       HR  2023-04-11
6   107      Arun  28.0    Male      NaN    Sales  2022-09-25
7   108       NaN  30.0  Female  55000.0  Finance  2021-10-12
8   109     David  25.0    Male  42000.0      NaN  2023-02-14
9   110     Meera   NaN  Female  48000.0       IT  2022-08-09
10  111       Ali  32.0    Male  62000.0       HR  2020-05-15
11  112   Fathima  29.0  Female      NaN  Finance  2021-11-30
12  113     Rohit  26.0    Male  41000.0    Sales  2023-03-17
13  114     Nisha  27.0  Female  53000.0       IT         NaN
14  115     Kiran  24.0    Male      NaN       HR  2022-06-28
15  116    Anjali   NaN  Female  50000.0  Finance  2023-01-19
16  117     Vijay  35.0    Male  70000.0       IT  2019-09-15
17  118     Pooja  28.0  Female  46000.0      NaN  2023-07-20
18  119     Samir  30.0    Male  58000.0    Sales         NaN
19  120      Neha  25.0  Female      NaN       HR  2022-04-16
20  121     Akash  27.0    Male  49000.0       IT  2023-06-01
21  122   Lakshmi  31.0  Female  61000.0  Finance  2021-12-22
22  123    Farhan   NaN    Male  45000.0    Sales  2022-03-18
23  124      Diya  29.0  Female  54000.0       HR         NaN
24  125     Kevin  26.0    Male      NaN       IT  2023-05-30
25  126      Riya  24.0  Female  43000.0  Finance  2022-02-14
26  127    Sanjay  33.0    Male  68000.0    Sales  2020-10-08
27  128       Anu   NaN  Female      NaN       HR  2023-01-07
28  129    Thomas  30.0    Male  59000.0       IT  2021-08-26
29  130    Reshma  27.0  Female  51000.0  Finance         NaN

In [82]:
df.columns=["Emp_ID","Name","Age","Gender","Salary","Department","Joining_Date"]
df

    Emp_ID      Name   Age  Gender   Salary Department Joining_Date
0      101  Mohammed  24.0    Male  45000.0         IT   2023-01-15
1      102     Aisha  27.0  Female  52000.0         HR   2022-11-10
2      103     Rahul   NaN    Male  38000.0      Sales   2023-05-21
3      104     Priya  29.0  Female      NaN    Finance   2021-07-18
4      105      John  31.0    Male  60000.0         IT          NaN
5      106     Sneha  26.0  Female  47000.0         HR   2023-04-11
6      107      Arun  28.0    Male      NaN      Sales   2022-09-25
7      108       NaN  30.0  Female  55000.0    Finance   2021-10-12
8      109     David  25.0    Male  42000.0        NaN   2023-02-14
9      110     Meera   NaN  Female  48000.0         IT   2022-08-09
10     111       Ali  32.0    Male  62000.0         HR   2020-05-15
11     112   Fathima  29.0  Female      NaN    Finance   2021-11-30
12     113     Rohit  26.0    Male  41000.0      Sales   2023-03-17
13     114     Nisha  27.0  Female  53000.0         IT          NaN
14     115     Kiran  24.0    Male      NaN         HR   2022-06-28
15     116    Anjali   NaN  Female  50000.0    Finance   2023-01-19
16     117     Vijay  35.0    Male  70000.0         IT   2019-09-15
17     118     Pooja  28.0  Female  46000.0        NaN   2023-07-20
18     119     Samir  30.0    Male  58000.0      Sales          NaN
19     120      Neha  25.0  Female      NaN         HR   2022-04-16
20     121     Akash  27.0    Male  49000.0         IT   2023-06-01
21     122   Lakshmi  31.0  Female  61000.0    Finance   2021-12-22
22     123    Farhan   NaN    Male  45000.0      Sales   2022-03-18
23     124      Diya  29.0  Female  54000.0         HR          NaN
24     125     Kevin  26.0    Male      NaN         IT   2023-05-30
25     126      Riya  24.0  Female  43000.0    Finance   2022-02-14
26     127    Sanjay  33.0    Male  68000.0      Sales   2020-10-08
27     128       Anu   NaN  Female      NaN         HR   2023-01-07
28     129    Thomas  30.0    Male  59000.0         IT   2021-08-26
29     130    Reshma  27.0  Female  51000.0    Finance          NaN

In [47]:
df.head(10)

   Emp_ID      Name   Age  Gender   Salary Department Joining_Date
0     101  Mohammed  24.0    Male  45000.0         IT   2023-01-15
1     102     Aisha  27.0  Female  52000.0         HR   2022-11-10
2     103     Rahul   NaN    Male  38000.0      Sales   2023-05-21
3     104     Priya  29.0  Female      NaN    Finance   2021-07-18
4     105      John  31.0    Male  60000.0         IT          NaN
5     106     Sneha  26.0  Female  47000.0         HR   2023-04-11
6     107      Arun  28.0    Male      NaN      Sales   2022-09-25
7     108       NaN  30.0  Female  55000.0    Finance   2021-10-12
8     109     David  25.0    Male  42000.0        NaN   2023-02-14
9     110     Meera   NaN  Female  48000.0         IT   2022-08-09

In [8]:
df.shape

(30, 7)

In [10]:
df.isna().sum()

Emp_ID          0
Name            1
Age             5
Gender          0
Salary          7
Department      2
Joining_Date    5
dtype: int64

In [48]:
df["Name"]=df["Name"].fillna("Unknown")
df

    Emp_ID      Name   Age  Gender   Salary Department Joining_Date
0      101  Mohammed  24.0    Male  45000.0         IT   2023-01-15
1      102     Aisha  27.0  Female  52000.0         HR   2022-11-10
2      103     Rahul   NaN    Male  38000.0      Sales   2023-05-21
3      104     Priya  29.0  Female      NaN    Finance   2021-07-18
4      105      John  31.0    Male  60000.0         IT          NaN
5      106     Sneha  26.0  Female  47000.0         HR   2023-04-11
6      107      Arun  28.0    Male      NaN      Sales   2022-09-25
7      108   Unknown  30.0  Female  55000.0    Finance   2021-10-12
8      109     David  25.0    Male  42000.0        NaN   2023-02-14
9      110     Meera   NaN  Female  48000.0         IT   2022-08-09
10     111       Ali  32.0    Male  62000.0         HR   2020-05-15
11     112   Fathima  29.0  Female      NaN    Finance   2021-11-30
12     113     Rohit  26.0    Male  41000.0      Sales   2023-03-17
13     114     Nisha  27.0  Female  53000.0         IT          NaN
14     115     Kiran  24.0    Male      NaN         HR   2022-06-28
15     116    Anjali   NaN  Female  50000.0    Finance   2023-01-19
16     117     Vijay  35.0    Male  70000.0         IT   2019-09-15
17     118     Pooja  28.0  Female  46000.0        NaN   2023-07-20
18     119     Samir  30.0    Male  58000.0      Sales          NaN
19     120      Neha  25.0  Female      NaN         HR   2022-04-16
20     121     Akash  27.0    Male  49000.0         IT   2023-06-01
21     122   Lakshmi  31.0  Female  61000.0    Finance   2021-12-22
22     123    Farhan   NaN    Male  45000.0      Sales   2022-03-18
23     124      Diya  29.0  Female  54000.0         HR          NaN
24     125     Kevin  26.0    Male      NaN         IT   2023-05-30
25     126      Riya  24.0  Female  43000.0    Finance   2022-02-14
26     127    Sanjay  33.0    Male  68000.0      Sales   2020-10-08
27     128       Anu   NaN  Female      NaN         HR   2023-01-07
28     129    Thomas  30.0    Male  59000.0         IT   2021-08-26
29     130    Reshma  27.0  Female  51000.0    Finance          NaN

In [49]:
df["Age"]=df["Age"].fillna(df["Age"].mean())
df

    Emp_ID      Name    Age  Gender   Salary Department Joining_Date
0      101  Mohammed  24.00    Male  45000.0         IT   2023-01-15
1      102     Aisha  27.00  Female  52000.0         HR   2022-11-10
2      103     Rahul  28.12    Male  38000.0      Sales   2023-05-21
3      104     Priya  29.00  Female      NaN    Finance   2021-07-18
4      105      John  31.00    Male  60000.0         IT          NaN
5      106     Sneha  26.00  Female  47000.0         HR   2023-04-11
6      107      Arun  28.00    Male      NaN      Sales   2022-09-25
7      108   Unknown  30.00  Female  55000.0    Finance   2021-10-12
8      109     David  25.00    Male  42000.0        NaN   2023-02-14
9      110     Meera  28.12  Female  48000.0         IT   2022-08-09
10     111       Ali  32.00    Male  62000.0         HR   2020-05-15
11     112   Fathima  29.00  Female      NaN    Finance   2021-11-30
12     113     Rohit  26.00    Male  41000.0      Sales   2023-03-17
13     114     Nisha  27.00  Female  53000.0         IT          NaN
14     115     Kiran  24.00    Male      NaN         HR   2022-06-28
15     116    Anjali  28.12  Female  50000.0    Finance   2023-01-19
16     117     Vijay  35.00    Male  70000.0         IT   2019-09-15
17     118     Pooja  28.00  Female  46000.0        NaN   2023-07-20
18     119     Samir  30.00    Male  58000.0      Sales          NaN
19     120      Neha  25.00  Female      NaN         HR   2022-04-16
20     121     Akash  27.00    Male  49000.0         IT   2023-06-01
21     122   Lakshmi  31.00  Female  61000.0    Finance   2021-12-22
22     123    Farhan  28.12    Male  45000.0      Sales   2022-03-18
23     124      Diya  29.00  Female  54000.0         HR          NaN
24     125     Kevin  26.00    Male      NaN         IT   2023-05-30
25     126      Riya  24.00  Female  43000.0    Finance   2022-02-14
26     127    Sanjay  33.00    Male  68000.0      Sales   2020-10-08
27     128       Anu  28.12  Female      NaN         HR   2023-01-07
28     129    Thomas  30.00    Male  59000.0         IT   2021-08-26
29     130    Reshma  27.00  Female  51000.0    Finance          NaN

In [15]:
df.dtypes

Emp_ID            int64
Name                str
Age             float64
Gender              str
Salary           object
Department          str
Joining_Date        str
dtype: object

In [53]:
df["Salary"] = df["Salary"].astype(float)
df

    Emp_ID      Name    Age  Gender   Salary Department Joining_Date
0      101  Mohammed  24.00    Male  45000.0         IT   2023-01-15
1      102     Aisha  27.00  Female  52000.0         HR   2022-11-10
2      103     Rahul  28.12    Male  38000.0      Sales   2023-05-21
3      104     Priya  29.00  Female      NaN    Finance   2021-07-18
4      105      John  31.00    Male  60000.0         IT          NaN
5      106     Sneha  26.00  Female  47000.0         HR   2023-04-11
6      107      Arun  28.00    Male      NaN      Sales   2022-09-25
7      108   Unknown  30.00  Female  55000.0    Finance   2021-10-12
8      109     David  25.00    Male  42000.0        NaN   2023-02-14
9      110     Meera  28.12  Female  48000.0         IT   2022-08-09
10     111       Ali  32.00    Male  62000.0         HR   2020-05-15
11     112   Fathima  29.00  Female      NaN    Finance   2021-11-30
12     113     Rohit  26.00    Male  41000.0      Sales   2023-03-17
13     114     Nisha  27.00  Female  53000.0         IT          NaN
14     115     Kiran  24.00    Male      NaN         HR   2022-06-28
15     116    Anjali  28.12  Female  50000.0    Finance   2023-01-19
16     117     Vijay  35.00    Male  70000.0         IT   2019-09-15
17     118     Pooja  28.00  Female  46000.0        NaN   2023-07-20
18     119     Samir  30.00    Male  58000.0      Sales          NaN
19     120      Neha  25.00  Female      NaN         HR   2022-04-16
20     121     Akash  27.00    Male  49000.0         IT   2023-06-01
21     122   Lakshmi  31.00  Female  61000.0    Finance   2021-12-22
22     123    Farhan  28.12    Male  45000.0      Sales   2022-03-18
23     124      Diya  29.00  Female  54000.0         HR          NaN
24     125     Kevin  26.00    Male      NaN         IT   2023-05-30
25     126      Riya  24.00  Female  43000.0    Finance   2022-02-14
26     127    Sanjay  33.00    Male  68000.0      Sales   2020-10-08
27     128       Anu  28.12  Female      NaN         HR   2023-01-07
28     129    Thomas  30.00    Male  59000.0         IT   2021-08-26
29     130    Reshma  27.00  Female  51000.0    Finance          NaN

In [54]:
df["Salary"] = df["Salary"].fillna(df["Salary"].median())
df

    Emp_ID      Name    Age  Gender   Salary Department Joining_Date
0      101  Mohammed  24.00    Male  45000.0         IT   2023-01-15
1      102     Aisha  27.00  Female  52000.0         HR   2022-11-10
2      103     Rahul  28.12    Male  38000.0      Sales   2023-05-21
3      104     Priya  29.00  Female  51000.0    Finance   2021-07-18
4      105      John  31.00    Male  60000.0         IT          NaN
5      106     Sneha  26.00  Female  47000.0         HR   2023-04-11
6      107      Arun  28.00    Male  51000.0      Sales   2022-09-25
7      108   Unknown  30.00  Female  55000.0    Finance   2021-10-12
8      109     David  25.00    Male  42000.0        NaN   2023-02-14
9      110     Meera  28.12  Female  48000.0         IT   2022-08-09
10     111       Ali  32.00    Male  62000.0         HR   2020-05-15
11     112   Fathima  29.00  Female  51000.0    Finance   2021-11-30
12     113     Rohit  26.00    Male  41000.0      Sales   2023-03-17
13     114     Nisha  27.00  Female  53000.0         IT          NaN
14     115     Kiran  24.00    Male  51000.0         HR   2022-06-28
15     116    Anjali  28.12  Female  50000.0    Finance   2023-01-19
16     117     Vijay  35.00    Male  70000.0         IT   2019-09-15
17     118     Pooja  28.00  Female  46000.0        NaN   2023-07-20
18     119     Samir  30.00    Male  58000.0      Sales          NaN
19     120      Neha  25.00  Female  51000.0         HR   2022-04-16
20     121     Akash  27.00    Male  49000.0         IT   2023-06-01
21     122   Lakshmi  31.00  Female  61000.0    Finance   2021-12-22
22     123    Farhan  28.12    Male  45000.0      Sales   2022-03-18
23     124      Diya  29.00  Female  54000.0         HR          NaN
24     125     Kevin  26.00    Male  51000.0         IT   2023-05-30
25     126      Riya  24.00  Female  43000.0    Finance   2022-02-14
26     127    Sanjay  33.00    Male  68000.0      Sales   2020-10-08
27     128       Anu  28.12  Female  51000.0         HR   2023-01-07
28     129    Thomas  30.00    Male  59000.0         IT   2021-08-26
29     130    Reshma  27.00  Female  51000.0    Finance          NaN

In [55]:
df["Department"]=df["Department"].fillna(df["Department"].mode()[0])
df

    Emp_ID      Name    Age  Gender   Salary Department Joining_Date
0      101  Mohammed  24.00    Male  45000.0         IT   2023-01-15
1      102     Aisha  27.00  Female  52000.0         HR   2022-11-10
2      103     Rahul  28.12    Male  38000.0      Sales   2023-05-21
3      104     Priya  29.00  Female  51000.0    Finance   2021-07-18
4      105      John  31.00    Male  60000.0         IT          NaN
5      106     Sneha  26.00  Female  47000.0         HR   2023-04-11
6      107      Arun  28.00    Male  51000.0      Sales   2022-09-25
7      108   Unknown  30.00  Female  55000.0    Finance   2021-10-12
8      109     David  25.00    Male  42000.0         IT   2023-02-14
9      110     Meera  28.12  Female  48000.0         IT   2022-08-09
10     111       Ali  32.00    Male  62000.0         HR   2020-05-15
11     112   Fathima  29.00  Female  51000.0    Finance   2021-11-30
12     113     Rohit  26.00    Male  41000.0      Sales   2023-03-17
13     114     Nisha  27.00  Female  53000.0         IT          NaN
14     115     Kiran  24.00    Male  51000.0         HR   2022-06-28
15     116    Anjali  28.12  Female  50000.0    Finance   2023-01-19
16     117     Vijay  35.00    Male  70000.0         IT   2019-09-15
17     118     Pooja  28.00  Female  46000.0         IT   2023-07-20
18     119     Samir  30.00    Male  58000.0      Sales          NaN
19     120      Neha  25.00  Female  51000.0         HR   2022-04-16
20     121     Akash  27.00    Male  49000.0         IT   2023-06-01
21     122   Lakshmi  31.00  Female  61000.0    Finance   2021-12-22
22     123    Farhan  28.12    Male  45000.0      Sales   2022-03-18
23     124      Diya  29.00  Female  54000.0         HR          NaN
24     125     Kevin  26.00    Male  51000.0         IT   2023-05-30
25     126      Riya  24.00  Female  43000.0    Finance   2022-02-14
26     127    Sanjay  33.00    Male  68000.0      Sales   2020-10-08
27     128       Anu  28.12  Female  51000.0         HR   2023-01-07
28     129    Thomas  30.00    Male  59000.0         IT   2021-08-26
29     130    Reshma  27.00  Female  51000.0    Finance          NaN

In [56]:
df["Joining_Date"]=df["Joining_Date"].fillna("2023-01-01")
df

    Emp_ID      Name    Age  Gender   Salary Department Joining_Date
0      101  Mohammed  24.00    Male  45000.0         IT   2023-01-15
1      102     Aisha  27.00  Female  52000.0         HR   2022-11-10
2      103     Rahul  28.12    Male  38000.0      Sales   2023-05-21
3      104     Priya  29.00  Female  51000.0    Finance   2021-07-18
4      105      John  31.00    Male  60000.0         IT   2023-01-01
5      106     Sneha  26.00  Female  47000.0         HR   2023-04-11
6      107      Arun  28.00    Male  51000.0      Sales   2022-09-25
7      108   Unknown  30.00  Female  55000.0    Finance   2021-10-12
8      109     David  25.00    Male  42000.0         IT   2023-02-14
9      110     Meera  28.12  Female  48000.0         IT   2022-08-09
10     111       Ali  32.00    Male  62000.0         HR   2020-05-15
11     112   Fathima  29.00  Female  51000.0    Finance   2021-11-30
12     113     Rohit  26.00    Male  41000.0      Sales   2023-03-17
13     114     Nisha  27.00  Female  53000.0         IT   2023-01-01
14     115     Kiran  24.00    Male  51000.0         HR   2022-06-28
15     116    Anjali  28.12  Female  50000.0    Finance   2023-01-19
16     117     Vijay  35.00    Male  70000.0         IT   2019-09-15
17     118     Pooja  28.00  Female  46000.0         IT   2023-07-20
18     119     Samir  30.00    Male  58000.0      Sales   2023-01-01
19     120      Neha  25.00  Female  51000.0         HR   2022-04-16
20     121     Akash  27.00    Male  49000.0         IT   2023-06-01
21     122   Lakshmi  31.00  Female  61000.0    Finance   2021-12-22
22     123    Farhan  28.12    Male  45000.0      Sales   2022-03-18
23     124      Diya  29.00  Female  54000.0         HR   2023-01-01
24     125     Kevin  26.00    Male  51000.0         IT   2023-05-30
25     126      Riya  24.00  Female  43000.0    Finance   2022-02-14
26     127    Sanjay  33.00    Male  68000.0      Sales   2020-10-08
27     128       Anu  28.12  Female  51000.0         HR   2023-01-07
28     129    Thomas  30.00    Male  59000.0         IT   2021-08-26
29     130    Reshma  27.00  Female  51000.0    Finance   2023-01-01

In [58]:
df.isna().sum()

Emp_ID          0
Name            0
Age             0
Gender          0
Salary          0
Department      0
Joining_Date    0
dtype: int64

In [60]:
df["Emp_ID"]=df["Emp_ID"].astype(int)
df

    Emp_ID      Name    Age  Gender   Salary Department Joining_Date
0      101  Mohammed  24.00    Male  45000.0         IT   2023-01-15
1      102     Aisha  27.00  Female  52000.0         HR   2022-11-10
2      103     Rahul  28.12    Male  38000.0      Sales   2023-05-21
3      104     Priya  29.00  Female  51000.0    Finance   2021-07-18
4      105      John  31.00    Male  60000.0         IT   2023-01-01
5      106     Sneha  26.00  Female  47000.0         HR   2023-04-11
6      107      Arun  28.00    Male  51000.0      Sales   2022-09-25
7      108   Unknown  30.00  Female  55000.0    Finance   2021-10-12
8      109     David  25.00    Male  42000.0         IT   2023-02-14
9      110     Meera  28.12  Female  48000.0         IT   2022-08-09
10     111       Ali  32.00    Male  62000.0         HR   2020-05-15
11     112   Fathima  29.00  Female  51000.0    Finance   2021-11-30
12     113     Rohit  26.00    Male  41000.0      Sales   2023-03-17
13     114     Nisha  27.00  Female  53000.0         IT   2023-01-01
14     115     Kiran  24.00    Male  51000.0         HR   2022-06-28
15     116    Anjali  28.12  Female  50000.0    Finance   2023-01-19
16     117     Vijay  35.00    Male  70000.0         IT   2019-09-15
17     118     Pooja  28.00  Female  46000.0         IT   2023-07-20
18     119     Samir  30.00    Male  58000.0      Sales   2023-01-01
19     120      Neha  25.00  Female  51000.0         HR   2022-04-16
20     121     Akash  27.00    Male  49000.0         IT   2023-06-01
21     122   Lakshmi  31.00  Female  61000.0    Finance   2021-12-22
22     123    Farhan  28.12    Male  45000.0      Sales   2022-03-18
23     124      Diya  29.00  Female  54000.0         HR   2023-01-01
24     125     Kevin  26.00    Male  51000.0         IT   2023-05-30
25     126      Riya  24.00  Female  43000.0    Finance   2022-02-14
26     127    Sanjay  33.00    Male  68000.0      Sales   2020-10-08
27     128       Anu  28.12  Female  51000.0         HR   2023-01-07
28     129    Thomas  30.00    Male  59000.0         IT   2021-08-26
29     130    Reshma  27.00  Female  51000.0    Finance   2023-01-01

In [61]:
df["Age"]=df["Age"].astype(int)
df

    Emp_ID      Name  Age  Gender   Salary Department Joining_Date
0      101  Mohammed   24    Male  45000.0         IT   2023-01-15
1      102     Aisha   27  Female  52000.0         HR   2022-11-10
2      103     Rahul   28    Male  38000.0      Sales   2023-05-21
3      104     Priya   29  Female  51000.0    Finance   2021-07-18
4      105      John   31    Male  60000.0         IT   2023-01-01
5      106     Sneha   26  Female  47000.0         HR   2023-04-11
6      107      Arun   28    Male  51000.0      Sales   2022-09-25
7      108   Unknown   30  Female  55000.0    Finance   2021-10-12
8      109     David   25    Male  42000.0         IT   2023-02-14
9      110     Meera   28  Female  48000.0         IT   2022-08-09
10     111       Ali   32    Male  62000.0         HR   2020-05-15
11     112   Fathima   29  Female  51000.0    Finance   2021-11-30
12     113     Rohit   26    Male  41000.0      Sales   2023-03-17
13     114     Nisha   27  Female  53000.0         IT   2023-01-01
14     115     Kiran   24    Male  51000.0         HR   2022-06-28
15     116    Anjali   28  Female  50000.0    Finance   2023-01-19
16     117     Vijay   35    Male  70000.0         IT   2019-09-15
17     118     Pooja   28  Female  46000.0         IT   2023-07-20
18     119     Samir   30    Male  58000.0      Sales   2023-01-01
19     120      Neha   25  Female  51000.0         HR   2022-04-16
20     121     Akash   27    Male  49000.0         IT   2023-06-01
21     122   Lakshmi   31  Female  61000.0    Finance   2021-12-22
22     123    Farhan   28    Male  45000.0      Sales   2022-03-18
23     124      Diya   29  Female  54000.0         HR   2023-01-01
24     125     Kevin   26    Male  51000.0         IT   2023-05-30
25     126      Riya   24  Female  43000.0    Finance   2022-02-14
26     127    Sanjay   33    Male  68000.0      Sales   2020-10-08
27     128       Anu   28  Female  51000.0         HR   2023-01-07
28     129    Thomas   30    Male  59000.0         IT   2021-08-26
29     130    Reshma   27  Female  51000.0    Finance   2023-01-01

In [62]:
df["Salary"]=df["Salary"].astype(float)
df

    Emp_ID      Name  Age  Gender   Salary Department Joining_Date
0      101  Mohammed   24    Male  45000.0         IT   2023-01-15
1      102     Aisha   27  Female  52000.0         HR   2022-11-10
2      103     Rahul   28    Male  38000.0      Sales   2023-05-21
3      104     Priya   29  Female  51000.0    Finance   2021-07-18
4      105      John   31    Male  60000.0         IT   2023-01-01
5      106     Sneha   26  Female  47000.0         HR   2023-04-11
6      107      Arun   28    Male  51000.0      Sales   2022-09-25
7      108   Unknown   30  Female  55000.0    Finance   2021-10-12
8      109     David   25    Male  42000.0         IT   2023-02-14
9      110     Meera   28  Female  48000.0         IT   2022-08-09
10     111       Ali   32    Male  62000.0         HR   2020-05-15
11     112   Fathima   29  Female  51000.0    Finance   2021-11-30
12     113     Rohit   26    Male  41000.0      Sales   2023-03-17
13     114     Nisha   27  Female  53000.0         IT   2023-01-01
14     115     Kiran   24    Male  51000.0         HR   2022-06-28
15     116    Anjali   28  Female  50000.0    Finance   2023-01-19
16     117     Vijay   35    Male  70000.0         IT   2019-09-15
17     118     Pooja   28  Female  46000.0         IT   2023-07-20
18     119     Samir   30    Male  58000.0      Sales   2023-01-01
19     120      Neha   25  Female  51000.0         HR   2022-04-16
20     121     Akash   27    Male  49000.0         IT   2023-06-01
21     122   Lakshmi   31  Female  61000.0    Finance   2021-12-22
22     123    Farhan   28    Male  45000.0      Sales   2022-03-18
23     124      Diya   29  Female  54000.0         HR   2023-01-01
24     125     Kevin   26    Male  51000.0         IT   2023-05-30
25     126      Riya   24  Female  43000.0    Finance   2022-02-14
26     127    Sanjay   33    Male  68000.0      Sales   2020-10-08
27     128       Anu   28  Female  51000.0         HR   2023-01-07
28     129    Thomas   30    Male  59000.0         IT   2021-08-26
29     130    Reshma   27  Female  51000.0    Finance   2023-01-01

In [63]:
df["Joining_Date"]=pd.to_datetime(df["Joining_Date"])
df

    Emp_ID      Name  Age  Gender   Salary Department Joining_Date
0      101  Mohammed   24    Male  45000.0         IT   2023-01-15
1      102     Aisha   27  Female  52000.0         HR   2022-11-10
2      103     Rahul   28    Male  38000.0      Sales   2023-05-21
3      104     Priya   29  Female  51000.0    Finance   2021-07-18
4      105      John   31    Male  60000.0         IT   2023-01-01
5      106     Sneha   26  Female  47000.0         HR   2023-04-11
6      107      Arun   28    Male  51000.0      Sales   2022-09-25
7      108   Unknown   30  Female  55000.0    Finance   2021-10-12
8      109     David   25    Male  42000.0         IT   2023-02-14
9      110     Meera   28  Female  48000.0         IT   2022-08-09
10     111       Ali   32    Male  62000.0         HR   2020-05-15
11     112   Fathima   29  Female  51000.0    Finance   2021-11-30
12     113     Rohit   26    Male  41000.0      Sales   2023-03-17
13     114     Nisha   27  Female  53000.0         IT   2023-01-01
14     115     Kiran   24    Male  51000.0         HR   2022-06-28
15     116    Anjali   28  Female  50000.0    Finance   2023-01-19
16     117     Vijay   35    Male  70000.0         IT   2019-09-15
17     118     Pooja   28  Female  46000.0         IT   2023-07-20
18     119     Samir   30    Male  58000.0      Sales   2023-01-01
19     120      Neha   25  Female  51000.0         HR   2022-04-16
20     121     Akash   27    Male  49000.0         IT   2023-06-01
21     122   Lakshmi   31  Female  61000.0    Finance   2021-12-22
22     123    Farhan   28    Male  45000.0      Sales   2022-03-18
23     124      Diya   29  Female  54000.0         HR   2023-01-01
24     125     Kevin   26    Male  51000.0         IT   2023-05-30
25     126      Riya   24  Female  43000.0    Finance   2022-02-14
26     127    Sanjay   33    Male  68000.0      Sales   2020-10-08
27     128       Anu   28  Female  51000.0         HR   2023-01-07
28     129    Thomas   30    Male  59000.0         IT   2021-08-26
29     130    Reshma   27  Female  51000.0    Finance   2023-01-01

In [65]:
df["Gender"] = df["Gender"].astype("category")
df

    Emp_ID      Name  Age  Gender   Salary Department Joining_Date
0      101  Mohammed   24    Male  45000.0         IT   2023-01-15
1      102     Aisha   27  Female  52000.0         HR   2022-11-10
2      103     Rahul   28    Male  38000.0      Sales   2023-05-21
3      104     Priya   29  Female  51000.0    Finance   2021-07-18
4      105      John   31    Male  60000.0         IT   2023-01-01
5      106     Sneha   26  Female  47000.0         HR   2023-04-11
6      107      Arun   28    Male  51000.0      Sales   2022-09-25
7      108   Unknown   30  Female  55000.0    Finance   2021-10-12
8      109     David   25    Male  42000.0         IT   2023-02-14
9      110     Meera   28  Female  48000.0         IT   2022-08-09
10     111       Ali   32    Male  62000.0         HR   2020-05-15
11     112   Fathima   29  Female  51000.0    Finance   2021-11-30
12     113     Rohit   26    Male  41000.0      Sales   2023-03-17
13     114     Nisha   27  Female  53000.0         IT   2023-01-01
14     115     Kiran   24    Male  51000.0         HR   2022-06-28
15     116    Anjali   28  Female  50000.0    Finance   2023-01-19
16     117     Vijay   35    Male  70000.0         IT   2019-09-15
17     118     Pooja   28  Female  46000.0         IT   2023-07-20
18     119     Samir   30    Male  58000.0      Sales   2023-01-01
19     120      Neha   25  Female  51000.0         HR   2022-04-16
20     121     Akash   27    Male  49000.0         IT   2023-06-01
21     122   Lakshmi   31  Female  61000.0    Finance   2021-12-22
22     123    Farhan   28    Male  45000.0      Sales   2022-03-18
23     124      Diya   29  Female  54000.0         HR   2023-01-01
24     125     Kevin   26    Male  51000.0         IT   2023-05-30
25     126      Riya   24  Female  43000.0    Finance   2022-02-14
26     127    Sanjay   33    Male  68000.0      Sales   2020-10-08
27     128       Anu   28  Female  51000.0         HR   2023-01-07
28     129    Thomas   30    Male  59000.0         IT   2021-08-26
29     130    Reshma   27  Female  51000.0    Finance   2023-01-01

In [66]:
df["Department"] = df["Department"].astype("category")
df

    Emp_ID      Name  Age  Gender   Salary Department Joining_Date
0      101  Mohammed   24    Male  45000.0         IT   2023-01-15
1      102     Aisha   27  Female  52000.0         HR   2022-11-10
2      103     Rahul   28    Male  38000.0      Sales   2023-05-21
3      104     Priya   29  Female  51000.0    Finance   2021-07-18
4      105      John   31    Male  60000.0         IT   2023-01-01
5      106     Sneha   26  Female  47000.0         HR   2023-04-11
6      107      Arun   28    Male  51000.0      Sales   2022-09-25
7      108   Unknown   30  Female  55000.0    Finance   2021-10-12
8      109     David   25    Male  42000.0         IT   2023-02-14
9      110     Meera   28  Female  48000.0         IT   2022-08-09
10     111       Ali   32    Male  62000.0         HR   2020-05-15
11     112   Fathima   29  Female  51000.0    Finance   2021-11-30
12     113     Rohit   26    Male  41000.0      Sales   2023-03-17
13     114     Nisha   27  Female  53000.0         IT   2023-01-01
14     115     Kiran   24    Male  51000.0         HR   2022-06-28
15     116    Anjali   28  Female  50000.0    Finance   2023-01-19
16     117     Vijay   35    Male  70000.0         IT   2019-09-15
17     118     Pooja   28  Female  46000.0         IT   2023-07-20
18     119     Samir   30    Male  58000.0      Sales   2023-01-01
19     120      Neha   25  Female  51000.0         HR   2022-04-16
20     121     Akash   27    Male  49000.0         IT   2023-06-01
21     122   Lakshmi   31  Female  61000.0    Finance   2021-12-22
22     123    Farhan   28    Male  45000.0      Sales   2022-03-18
23     124      Diya   29  Female  54000.0         HR   2023-01-01
24     125     Kevin   26    Male  51000.0         IT   2023-05-30
25     126      Riya   24  Female  43000.0    Finance   2022-02-14
26     127    Sanjay   33    Male  68000.0      Sales   2020-10-08
27     128       Anu   28  Female  51000.0         HR   2023-01-07
28     129    Thomas   30    Male  59000.0         IT   2021-08-26
29     130    Reshma   27  Female  51000.0    Finance   2023-01-01

In [67]:
print(df.dtypes)

Emp_ID                   int64
Name                       str
Age                      int64
Gender                category
Salary                 float64
Department            category
Joining_Date    datetime64[us]
dtype: object

In [68]:
df[df.isna().any(axis=1)]
df

    Emp_ID      Name  Age  Gender   Salary Department Joining_Date
0      101  Mohammed   24    Male  45000.0         IT   2023-01-15
1      102     Aisha   27  Female  52000.0         HR   2022-11-10
2      103     Rahul   28    Male  38000.0      Sales   2023-05-21
3      104     Priya   29  Female  51000.0    Finance   2021-07-18
4      105      John   31    Male  60000.0         IT   2023-01-01
5      106     Sneha   26  Female  47000.0         HR   2023-04-11
6      107      Arun   28    Male  51000.0      Sales   2022-09-25
7      108   Unknown   30  Female  55000.0    Finance   2021-10-12
8      109     David   25    Male  42000.0         IT   2023-02-14
9      110     Meera   28  Female  48000.0         IT   2022-08-09
10     111       Ali   32    Male  62000.0         HR   2020-05-15
11     112   Fathima   29  Female  51000.0    Finance   2021-11-30
12     113     Rohit   26    Male  41000.0      Sales   2023-03-17
13     114     Nisha   27  Female  53000.0         IT   2023-01-01
14     115     Kiran   24    Male  51000.0         HR   2022-06-28
15     116    Anjali   28  Female  50000.0    Finance   2023-01-19
16     117     Vijay   35    Male  70000.0         IT   2019-09-15
17     118     Pooja   28  Female  46000.0         IT   2023-07-20
18     119     Samir   30    Male  58000.0      Sales   2023-01-01
19     120      Neha   25  Female  51000.0         HR   2022-04-16
20     121     Akash   27    Male  49000.0         IT   2023-06-01
21     122   Lakshmi   31  Female  61000.0    Finance   2021-12-22
22     123    Farhan   28    Male  45000.0      Sales   2022-03-18
23     124      Diya   29  Female  54000.0         HR   2023-01-01
24     125     Kevin   26    Male  51000.0         IT   2023-05-30
25     126      Riya   24  Female  43000.0    Finance   2022-02-14
26     127    Sanjay   33    Male  68000.0      Sales   2020-10-08
27     128       Anu   28  Female  51000.0         HR   2023-01-07
28     129    Thomas   30    Male  59000.0         IT   2021-08-26
29     130    Reshma   27  Female  51000.0    Finance   2023-01-01

In [76]:
df=df.dropna()
df

    Emp_ID      Name  Age  Gender   Salary Department Joining_Date
0      101  Mohammed   24    Male  45000.0         IT   2023-01-15
1      102     Aisha   27  Female  52000.0         HR   2022-11-10
2      103     Rahul   28    Male  38000.0      Sales   2023-05-21
3      104     Priya   29  Female  51000.0    Finance   2021-07-18
4      105      John   31    Male  60000.0         IT   2023-01-01
5      106     Sneha   26  Female  47000.0         HR   2023-04-11
6      107      Arun   28    Male  51000.0      Sales   2022-09-25
7      108   Unknown   30  Female  55000.0    Finance   2021-10-12
8      109     David   25    Male  42000.0         IT   2023-02-14
9      110     Meera   28  Female  48000.0         IT   2022-08-09
10     111       Ali   32    Male  62000.0         HR   2020-05-15
11     112   Fathima   29  Female  51000.0    Finance   2021-11-30
12     113     Rohit   26    Male  41000.0      Sales   2023-03-17
13     114     Nisha   27  Female  53000.0         IT   2023-01-01
14     115     Kiran   24    Male  51000.0         HR   2022-06-28
15     116    Anjali   28  Female  50000.0    Finance   2023-01-19
16     117     Vijay   35    Male  70000.0         IT   2019-09-15
17     118     Pooja   28  Female  46000.0         IT   2023-07-20
18     119     Samir   30    Male  58000.0      Sales   2023-01-01
19     120      Neha   25  Female  51000.0         HR   2022-04-16
20     121     Akash   27    Male  49000.0         IT   2023-06-01
21     122   Lakshmi   31  Female  61000.0    Finance   2021-12-22
22     123    Farhan   28    Male  45000.0      Sales   2022-03-18
23     124      Diya   29  Female  54000.0         HR   2023-01-01
24     125     Kevin   26    Male  51000.0         IT   2023-05-30
25     126      Riya   24  Female  43000.0    Finance   2022-02-14
26     127    Sanjay   33    Male  68000.0      Sales   2020-10-08
27     128       Anu   28  Female  51000.0         HR   2023-01-07
28     129    Thomas   30    Male  59000.0         IT   2021-08-26
29     130    Reshma   27  Female  51000.0    Finance   2023-01-01

In [79]:
df=df.dropna()
df

    Emp_ID      Name  Age  Gender   Salary Department Joining_Date
0      101  Mohammed   24    Male  45000.0         IT   2023-01-15
1      102     Aisha   27  Female  52000.0         HR   2022-11-10
2      103     Rahul   28    Male  38000.0      Sales   2023-05-21
3      104     Priya   29  Female  51000.0    Finance   2021-07-18
4      105      John   31    Male  60000.0         IT   2023-01-01
5      106     Sneha   26  Female  47000.0         HR   2023-04-11
6      107      Arun   28    Male  51000.0      Sales   2022-09-25
7      108   Unknown   30  Female  55000.0    Finance   2021-10-12
8      109     David   25    Male  42000.0         IT   2023-02-14
9      110     Meera   28  Female  48000.0         IT   2022-08-09
10     111       Ali   32    Male  62000.0         HR   2020-05-15
11     112   Fathima   29  Female  51000.0    Finance   2021-11-30
12     113     Rohit   26    Male  41000.0      Sales   2023-03-17
13     114     Nisha   27  Female  53000.0         IT   2023-01-01
14     115     Kiran   24    Male  51000.0         HR   2022-06-28
15     116    Anjali   28  Female  50000.0    Finance   2023-01-19
16     117     Vijay   35    Male  70000.0         IT   2019-09-15
17     118     Pooja   28  Female  46000.0         IT   2023-07-20
18     119     Samir   30    Male  58000.0      Sales   2023-01-01
19     120      Neha   25  Female  51000.0         HR   2022-04-16
20     121     Akash   27    Male  49000.0         IT   2023-06-01
21     122   Lakshmi   31  Female  61000.0    Finance   2021-12-22
22     123    Farhan   28    Male  45000.0      Sales   2022-03-18
23     124      Diya   29  Female  54000.0         HR   2023-01-01
24     125     Kevin   26    Male  51000.0         IT   2023-05-30
25     126      Riya   24  Female  43000.0    Finance   2022-02-14
26     127    Sanjay   33    Male  68000.0      Sales   2020-10-08
27     128       Anu   28  Female  51000.0         HR   2023-01-07
28     129    Thomas   30    Male  59000.0         IT   2021-08-26
29     130    Reshma   27  Female  51000.0    Finance   2023-01-01

In [83]:
print("Original Shape:", df.shape)
df

Original Shape: (30, 7)

    Emp_ID      Name   Age  Gender   Salary Department Joining_Date
0      101  Mohammed  24.0    Male  45000.0         IT   2023-01-15
1      102     Aisha  27.0  Female  52000.0         HR   2022-11-10
2      103     Rahul   NaN    Male  38000.0      Sales   2023-05-21
3      104     Priya  29.0  Female      NaN    Finance   2021-07-18
4      105      John  31.0    Male  60000.0         IT          NaN
5      106     Sneha  26.0  Female  47000.0         HR   2023-04-11
6      107      Arun  28.0    Male      NaN      Sales   2022-09-25
7      108       NaN  30.0  Female  55000.0    Finance   2021-10-12
8      109     David  25.0    Male  42000.0        NaN   2023-02-14
9      110     Meera   NaN  Female  48000.0         IT   2022-08-09
10     111       Ali  32.0    Male  62000.0         HR   2020-05-15
11     112   Fathima  29.0  Female      NaN    Finance   2021-11-30
12     113     Rohit  26.0    Male  41000.0      Sales   2023-03-17
13     114     Nisha  27.0  Female  53000.0         IT          NaN
14     115     Kiran  24.0    Male      NaN         HR   2022-06-28
15     116    Anjali   NaN  Female  50000.0    Finance   2023-01-19
16     117     Vijay  35.0    Male  70000.0         IT   2019-09-15
17     118     Pooja  28.0  Female  46000.0        NaN   2023-07-20
18     119     Samir  30.0    Male  58000.0      Sales          NaN
19     120      Neha  25.0  Female      NaN         HR   2022-04-16
20     121     Akash  27.0    Male  49000.0         IT   2023-06-01
21     122   Lakshmi  31.0  Female  61000.0    Finance   2021-12-22
22     123    Farhan   NaN    Male  45000.0      Sales   2022-03-18
23     124      Diya  29.0  Female  54000.0         HR          NaN
24     125     Kevin  26.0    Male      NaN         IT   2023-05-30
25     126      Riya  24.0  Female  43000.0    Finance   2022-02-14
26     127    Sanjay  33.0    Male  68000.0      Sales   2020-10-08
27     128       Anu   NaN  Female      NaN         HR   2023-01-07
28     129    Thomas  30.0    Male  59000.0         IT   2021-08-26
29     130    Reshma  27.0  Female  51000.0    Finance          NaN

In [85]:
df = df.dropna()
df

    Emp_ID      Name   Age  Gender   Salary Department Joining_Date
0      101  Mohammed  24.0    Male  45000.0         IT   2023-01-15
1      102     Aisha  27.0  Female  52000.0         HR   2022-11-10
5      106     Sneha  26.0  Female  47000.0         HR   2023-04-11
10     111       Ali  32.0    Male  62000.0         HR   2020-05-15
12     113     Rohit  26.0    Male  41000.0      Sales   2023-03-17
16     117     Vijay  35.0    Male  70000.0         IT   2019-09-15
20     121     Akash  27.0    Male  49000.0         IT   2023-06-01
21     122   Lakshmi  31.0  Female  61000.0    Finance   2021-12-22
25     126      Riya  24.0  Female  43000.0    Finance   2022-02-14
26     127    Sanjay  33.0    Male  68000.0      Sales   2020-10-08
28     129    Thomas  30.0    Male  59000.0         IT   2021-08-26

In [86]:
print("New Shape:", df.shape)

New Shape: (11, 7)