In [1]:
import pandas as pd

In [2]:
df = pd.read_excel(r"C:\Users\Nandhana\Downloads\numpy1\customer_34227636.xlsx")
df

          Id Firstname Lastname  Age                  Profession Location
0    4000001  Kristina    Chung   55                       Pilot    india
1    4000002     Paige     Chen   74                     Teacher       uk
2    4000003    Sherri   Melton   34                 Firefighter       us
3    4000004  Gretchen     Hill   66  Computer hardware engineer    china
4    4000005     Karen  Puckett   74                      Lawyer   africa
..       ...       ...      ...  ...                         ...      ...
458  4000459  Gretchen  Francis   60                  Politician  ireland
459  4000460    Cheryl     Horn   40                Veterinarian  ireland
460  4000461    Audrey  Forrest   50                   Architect  ireland
461  4000462      Alan    Levin   43                Statistician  ireland
462  4000463     Wayne   Weiner   70                       Actor  ireland

[463 rows x 6 columns]

In [3]:
df.head(2)

        Id Firstname Lastname  Age Profession Location
0  4000001  Kristina    Chung   55      Pilot    india
1  4000002     Paige     Chen   74    Teacher       uk

In [5]:
df.loc[:9,["Firstname","Lastname"]]

  Firstname    Lastname
0  Kristina       Chung
1     Paige        Chen
2    Sherri      Melton
3  Gretchen        Hill
4     Karen     Puckett
5   Patrick        Song
6     Elsie    Hamilton
7     Hazel      Bender
8   Malcolm      Wagner
9   Dolores  McLaughlin

In [7]:
df.loc[100:200,["Firstname","Profession"]]

    Firstname                     Profession
100     Scott                        Teacher
101      Gene  Recreation and fitness worker
102    Louise                   Loan officer
103  Geoffrey                   Photographer
104  Patricia                   Veterinarian
..        ...                            ...
196     Terry  Recreation and fitness worker
197       Ken            Automotive mechanic
198      Judy                        Athlete
199     Clyde                     Pharmacist
200   Timothy                      Librarian

[101 rows x 2 columns]

In [8]:
df.sort_values(by="Age")

          Id Firstname   Lastname  Age      Profession   Location
51   4000052   Shirley    Merritt   21        Reporter         uk
348  4000349   Russell     Dalton   21  Civil engineer  australia
291  4000292     Donna       Rice   21   Social worker  australia
289  4000290      Gail  Whitehead   21           Nurse  australia
450  4000451   Russell       Hess   21       Architect    ireland
..       ...       ...        ...  ...             ...        ...
403  4000404  Clarence     Massey   74      Politician    ireland
1    4000002     Paige       Chen   74         Teacher         uk
391  4000392      Emma      Olson   74           Pilot    ireland
324  4000325      Ruth     Harmon   75          Artist  australia
88   4000089    Sherri     Sutton   75   Social worker         us

[463 rows x 6 columns]

In [9]:
df.sort_values(by="Age")

          Id Firstname   Lastname  Age      Profession   Location
51   4000052   Shirley    Merritt   21        Reporter         uk
348  4000349   Russell     Dalton   21  Civil engineer  australia
291  4000292     Donna       Rice   21   Social worker  australia
289  4000290      Gail  Whitehead   21           Nurse  australia
450  4000451   Russell       Hess   21       Architect    ireland
..       ...       ...        ...  ...             ...        ...
403  4000404  Clarence     Massey   74      Politician    ireland
1    4000002     Paige       Chen   74         Teacher         uk
391  4000392      Emma      Olson   74           Pilot    ireland
324  4000325      Ruth     Harmon   75          Artist  australia
88   4000089    Sherri     Sutton   75   Social worker         us

[463 rows x 6 columns]

In [10]:
df.sort_values(by="Age",ascending=False)

          Id Firstname   Lastname  Age           Profession   Location
324  4000325      Ruth     Harmon   75               Artist  australia
88   4000089    Sherri     Sutton   75        Social worker         us
274  4000275  Lawrence      Miles   74               Dancer     africa
241  4000242      Edna      Hoyle   74  Electrical engineer     africa
258  4000259  Margaret    Burgess   74        Social worker     africa
..       ...       ...        ...  ...                  ...        ...
291  4000292     Donna       Rice   21        Social worker  australia
450  4000451   Russell       Hess   21            Architect    ireland
348  4000349   Russell     Dalton   21       Civil engineer  australia
175  4000176   Kristin  Alexander   21                Coach      china
51   4000052   Shirley    Merritt   21             Reporter         uk

[463 rows x 6 columns]

In [11]:
df.sort_values(by="Age").head(10)

          Id Firstname   Lastname  Age                  Profession   Location
51   4000052   Shirley    Merritt   21                    Reporter         uk
348  4000349   Russell     Dalton   21              Civil engineer  australia
291  4000292     Donna       Rice   21               Social worker  australia
289  4000290      Gail  Whitehead   21                       Nurse  australia
450  4000451   Russell       Hess   21                   Architect    ireland
175  4000176   Kristin  Alexander   21                       Coach      china
358  4000359      Leon     Bender   22                 Firefighter  australia
53   4000054    Judith     Cooper   22                   Economist         uk
453  4000454  Virginia     Turner   22  Computer hardware engineer    ireland
151  4000152   Vincent    Goldman   22                 Electrician      china

In [12]:
df.sort_values(by="Age").head(5)[["Firstname","Lastname"]]

    Firstname   Lastname
51    Shirley    Merritt
348   Russell     Dalton
291     Donna       Rice
289      Gail  Whitehead
450   Russell       Hess

In [13]:
df.sort_values(by="Age",ascending=False).head(2)[["Profession"]]

        Profession
324         Artist
88   Social worker

In [14]:
df[df["Location"]=="india"]

         Id Firstname    Lastname  Age                   Profession Location
0   4000001  Kristina       Chung   55                        Pilot    india
7   4000008     Hazel      Bender   63                    Carpenter    india
8   4000009   Malcolm      Wagner   39                       Artist    india
9   4000010   Dolores  McLaughlin   60                       Writer    india
10  4000011   Francis    McNamara   47                    Therapist    india
11  4000012     Sandy      Raynor   26                       Writer    india
12  4000013    Marion        Moon   41                    Carpenter    india
13  4000014      Beth     Woodard   65                     Musician    india
14  4000015     Julia       Desai   49                     Musician    india
15  4000016    Jerome     Wallace   52                   Pharmacist    india
16  4000017      Neal    Lawrence   72  Computer support specialist    india
17  4000018      Jean     Griffin   45             Childcare worker    india
18  4000019  Kristine   Dougherty   63            Financial analyst    india
19  4000020   Crystal      Powers   67       Engineering technician    india
20  4000021      Alex         May   39      Environmental scientist    india
21  4000022      Eric      Steele   66                       Doctor    india
22  4000023    Wesley      Teague   42                    Carpenter    india
23  4000024  Franklin        Vick   28                       Dancer    india
24  4000025    Claire   Gallagher   42                     Musician    india
25  4000026    Marian     Solomon   27                       Lawyer    india
26  4000027    Marcia       Walsh   64                   Accountant    india

In [16]:
df.reset_index(drop=True,inplace=True)
df

          Id Firstname Lastname  Age                  Profession Location
0    4000001  Kristina    Chung   55                       Pilot    india
1    4000002     Paige     Chen   74                     Teacher       uk
2    4000003    Sherri   Melton   34                 Firefighter       us
3    4000004  Gretchen     Hill   66  Computer hardware engineer    china
4    4000005     Karen  Puckett   74                      Lawyer   africa
..       ...       ...      ...  ...                         ...      ...
458  4000459  Gretchen  Francis   60                  Politician  ireland
459  4000460    Cheryl     Horn   40                Veterinarian  ireland
460  4000461    Audrey  Forrest   50                   Architect  ireland
461  4000462      Alan    Levin   43                Statistician  ireland
462  4000463     Wayne   Weiner   70                       Actor  ireland

[463 rows x 6 columns]

In [17]:
df[df["Profession"]=="Pilot"]

          Id  Firstname  Lastname  Age Profession   Location
0    4000001   Kristina     Chung   55      Pilot      india
6    4000007      Elsie  Hamilton   43      Pilot    ireland
228  4000229       Faye    Norman   64      Pilot     africa
229  4000230      Kathy     Burch   28      Pilot     africa
250  4000251     Jeremy     House   61      Pilot     africa
270  4000271      Alice     Nance   59      Pilot     africa
321  4000322  Geraldine    Jensen   50      Pilot  australia
335  4000336     Steven   Ballard   62      Pilot  australia
391  4000392       Emma     Olson   74      Pilot    ireland
402  4000403        Leo  Lassiter   65      Pilot    ireland
422  4000423       Alan    O'Neal   59      Pilot    ireland
424  4000425       Dean      Lutz   26      Pilot    ireland
439  4000440     Hannah  Langston   25      Pilot    ireland

In [18]:
df[df["Profession"]=="Dancer"][["Firstname","Lastname"]]

     Firstname  Lastname
23    Franklin      Vick
109       Kurt   Cassidy
115      Danny     Byrne
164     Ronnie    Atkins
274   Lawrence     Miles
356        Max  Robinson
389      Tracy     Cates
423  Christina    Morris
431      Paige    Henson

In [20]:
df[(df["Location"]=="uk")].sort_values(by="Age",ascending=False).head(1)[["Firstname","Lastname"]]

  Firstname Lastname
1     Paige     Chen

In [21]:
df[df["Location"]=="china"].shape[0]

56

In [22]:
df[(df["Profession"]=="Teacher") & (df["Location"]=="uk")].shape[0]

2

In [23]:
df[df["Location"]=="india"].shape[0]

21

In [24]:
df[df["Location"]=="us"]

          Id Firstname Lastname  Age                   Profession Location
2    4000003    Sherri   Melton   34                  Firefighter       us
63   4000064    Calvin     Diaz   65                      Athlete       us
64   4000065    Eugene   Graham   52               Police officer       us
65   4000066    Vickie  Watkins   55  Computer support specialist       us
66   4000067      Luis   Hinton   69             Childcare worker       us
..       ...       ...      ...  ...                          ...      ...
135  4000136    Dianne   Norman   68                 Veterinarian       us
136  4000137    Rhonda     Chan   34                   Pharmacist       us
137  4000138    Tamara     Hunt   25                 Psychologist       us
138  4000139      Mary     Byrd   34      Environmental scientist       us
139  4000140    Sidney     Lane   54                 Statistician       us

[78 rows x 6 columns]

In [26]:
df[df["Location"]=="china"][["Firstname","Lastname","Age"]].sort_values(by="Age")

     Firstname   Lastname  Age
175    Kristin  Alexander   21
151    Vincent    Goldman   22
153     Milton      Starr   23
144      Roger      Hanna   23
191     Alison  MacDonald   26
142      Katie        May   28
158       Glen     Abbott   29
170    Stephen      Finch   30
149     Martin       Vick   31
165     Martha     Monroe   31
160      Alice       Hall   33
161      Bruce    Farrell   35
174        Ben   Whitaker   35
179      Louis    Rollins   35
173      Doris     Kinney   36
182  Constance      Black   36
145    Natalie   Locklear   37
189        Kim   Matthews   38
180      Janet       Love   39
168     Robert       Reid   39
178       Mark     Becker   39
148       Neal     Glover   40
187     Jerome      Joyce   40
152       Beth    McKenna   40
181        Leo     Adkins   42
166       Lynn  Robertson   45
167       Jose      Sykes   47
186      Hazel      Lloyd   48
157      Leroy     Monroe   51
141     Sandra     Heller   51
176       Ryan     Conner   51
188    Vincent      Welch   54
194     Claire    Pickett   59
150       Jack  O'Donnell   59
190     Joseph   Chappell   59
192       Eric       Kane   61
163        Amy     Norman   62
184     Gladys    Hatcher   62
143    Raymond   Jennings   63
156   Franklin     Watson   64
146      Kathy   Holloway   65
3     Gretchen       Hill   66
162   Kathleen      Lucas   66
193    Heather     Butler   67
164     Ronnie     Atkins   67
155   Mitchell    McClure   68
185      Hazel         Wu   68
171      Peggy      Hobbs   69
140       Jeff     Kaplan   70
169    Pauline   Chandler   70
172      Donna     Adkins   72
154     Tamara      Stone   73
183      Sarah        Fox   73
159     Judith     Singer   73
177     Tracey     Waters   73
147       Troy      Jones   74

In [27]:
df[df["Location"]=="ireland"].sort_values(by="Age",ascending=False).head(1)

          Id Firstname Lastname  Age Profession Location
391  4000392      Emma    Olson   74      Pilot  ireland

In [28]:
df[df["Location"]=="india"].sort_values(by="Age").head(1)[["Profession"]]

   Profession
11     Writer

In [29]:
df[df["Age"]>70]

,Id,Firstname,Lastname,Age,Profession,Location
1,4000002,Paige,Chen,74,Teacher,uk
4,4000005,Karen,Puckett,74,Lawyer,africa
16,4000017,Neal,Lawrence,72,Computer support specialist,india
37,4000038,Beth,Walton,73,Firefighter,uk
86,4000087,Steve,Graves,73,Nurse,us
88,4000089,Sherri,Sutton,75,Social worker,us
99,4000100,Ronnie,Cowan,71,Photographer,us
101,4000102,Gene,Bowling,73,Recreation and fitness worker,us
112,4000113,Alice,Blanchard,73,Economist,us
113,4000114,Joan,McAllister,73,Engineering technician,us
131,4000132,Jessica,Hester,72,Civil engineer,us
132,4000133,Samantha,Floyd,72,Childcare worker,us
147,4000148,Troy,Jones,74,Secretary,china
154,4000155,Tamara,Stone,73,Firefighter,china
159,4000160,Judith,Singer,73,Actor,china
172,4000173,Donna,Adkins,72,Electrical engineer,china
177,4000178,Tracey,Waters,73,Computer hardware engineer,china
183,4000184,Sarah,Fox,73,Psychologist,china
210,4000211,Louis,Harvey,72,Financial analyst,africa
213,4000214,Sheryl,Dunn,71,Civil engineer,africa
219,4000220,Rebecca,Heath,74,Environmental scientist,africa
224,4000225,Randy,Petersen,71,Actor,africa
241,4000242,Edna,Hoyle,74,Electrical engineer,africa
242,4000243,Clifford,Garrett,72,Veterinarian,africa
253,4000254,Lucy,Dickinson,72,Loan officer,africa
258,4000259,Margaret,Burgess,74,Social worker,africa
268,4000269,Leroy,Donovan,74,Photographer,africa
274,4000275,Lawrence,Miles,74,Dancer,africa
284,4000285,Donna,Lehman,71,Social worker,australia
306,4000307,Karen,Clements,74,Farmer,australia
324,4000325,Ruth,Harmon,75,Artist,australia
337,4000338,Marc,Denton,71,Musician,australia
350,4000351,Lewis,Currin,73,Farmer,australia
359,4000360,Alvin,McDonald,73,Musician,australia
361,4000362,Holly,Fox,74,Physicist,australia
370,4000371,Harriet,Rubin,71,Real estate agent,australia
387,4000388,Jean,Garrett,73,Doctor,ireland
390,4000391,Holly,McIntosh,73,Computer software engineer,ireland
391,4000392,Emma,Olson,74,Pilot,ireland
399,4000400,Kelly,Weiss,72,Librarian,ireland
403,4000404,Clarence,Massey,74,Politician,ireland
413,4000414,Jessica,Teague,72,Firefighter,ireland
421,4000422,Tommy,Burnette,72,Doctor,ireland

In [31]:
df[(df["Age"]>50) & (df["Location"]=="china")][["Firstname","Profession"]]

    Firstname                   Profession
3    Gretchen   Computer hardware engineer
140      Jeff                      Chemist
141    Sandra                 Photographer
143   Raymond                        Coach
146     Kathy                   Pharmacist
147      Troy                    Secretary
150      Jack                        Actor
154    Tamara                  Firefighter
155  Mitchell                 Loan officer
156  Franklin                        Coach
157     Leroy  Computer support specialist
159    Judith                        Actor
162  Kathleen                      Chemist
163       Amy          Automotive mechanic
164    Ronnie                       Dancer
169   Pauline                    Economist
171     Peggy                     Musician
172     Donna          Electrical engineer
176      Ryan          Electrical engineer
177    Tracey   Computer hardware engineer
183     Sarah                 Psychologist
184    Gladys                     Musician
185     Hazel                    Therapist
188   Vincent                 Psychologist
190    Joseph                     Reporter
192      Eric             Childcare worker
193   Heather                       Farmer
194    Claire                       Lawyer

In [32]:
df[df["Profession"]=="Pilot"]

          Id  Firstname  Lastname  Age Profession   Location
0    4000001   Kristina     Chung   55      Pilot      india
6    4000007      Elsie  Hamilton   43      Pilot    ireland
228  4000229       Faye    Norman   64      Pilot     africa
229  4000230      Kathy     Burch   28      Pilot     africa
250  4000251     Jeremy     House   61      Pilot     africa
270  4000271      Alice     Nance   59      Pilot     africa
321  4000322  Geraldine    Jensen   50      Pilot  australia
335  4000336     Steven   Ballard   62      Pilot  australia
391  4000392       Emma     Olson   74      Pilot    ireland
402  4000403        Leo  Lassiter   65      Pilot    ireland
422  4000423       Alan    O'Neal   59      Pilot    ireland
424  4000425       Dean      Lutz   26      Pilot    ireland
439  4000440     Hannah  Langston   25      Pilot    ireland

In [34]:
df[(df["Profession"]=="Teacher") & (df["Location"]=="uk")]

         Id Firstname Lastname  Age Profession Location
1   4000002     Paige     Chen   74    Teacher       uk
62  4000063   Melinda  Proctor   27    Teacher       uk

In [36]:
df[(df["Profession"]=="Accountant") & (df["Location"]=="india")][["Firstname","Lastname"]]

   Firstname Lastname
26    Marcia    Walsh

In [37]:
df[(df["Profession"]=="Musician") & (df["Location"]=="india")].sort_values(by="Age",ascending=False).head(2)

         Id Firstname Lastname  Age Profession Location
13  4000014      Beth  Woodard   65   Musician    india
14  4000015     Julia    Desai   49   Musician    india

In [38]:
df.isnull().sum()

Id            0
Firstname     0
Lastname      0
Age           0
Profession    1
Location      0
dtype: int64

In [40]:
df[df["Profession"]=="Teacher"][["Firstname","Profession","Age"]].sort_values(by="Age",ascending=False)

    Firstname Profession  Age
1       Paige    Teacher   74
374    Norman    Teacher   63
62    Melinda    Teacher   27
100     Scott    Teacher   27
396      Bill    Teacher   26

In [42]:
df[(df["Profession"]=="Musician") & (df["Location"]=="india")].sort_values(by="Age",ascending=False).head(1)[["Firstname"]]

   Firstname
13      Beth

In [44]:
df[(df["Profession"]=="Dancer") & (df["Location"]=="india")].sort_values(by="Age").head(1)[["Firstname"]]

   Firstname
23  Franklin

In [45]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
458    False
459    False
460    False
461    False
462    False
Length: 463, dtype: bool

In [47]:
df.drop_duplicates(inplace=True)
df

          Id Firstname Lastname  Age                  Profession Location
0    4000001  Kristina    Chung   55                       Pilot    india
1    4000002     Paige     Chen   74                     Teacher       uk
2    4000003    Sherri   Melton   34                 Firefighter       us
3    4000004  Gretchen     Hill   66  Computer hardware engineer    china
4    4000005     Karen  Puckett   74                      Lawyer   africa
..       ...       ...      ...  ...                         ...      ...
458  4000459  Gretchen  Francis   60                  Politician  ireland
459  4000460    Cheryl     Horn   40                Veterinarian  ireland
460  4000461    Audrey  Forrest   50                   Architect  ireland
461  4000462      Alan    Levin   43                Statistician  ireland
462  4000463     Wayne   Weiner   70                       Actor  ireland

[463 rows x 6 columns]