HR Analytics

In [4]:
import pandas as pd

In [6]:
df = pd.read_excel(r"C:\Users\Nandhana\Downloads\numpy1\HR_Analytics_34227620.xlsx")
df

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,RM297,18,18-25,Yes,Travel_Rarely,230,Research & Development,3,3,Life Sciences,...,3,80,0,0,2,3,0,0,0,0.0
1,RM302,18,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,...,1,80,0,0,2,3,0,0,0,0.0
2,RM458,18,18-25,Yes,Travel_Frequently,1306,Sales,5,3,Marketing,...,4,80,0,0,3,3,0,0,0,0.0
3,RM728,18,18-25,No,Non-Travel,287,Research & Development,5,2,Life Sciences,...,4,80,0,0,2,3,0,0,0,0.0
4,RM829,18,18-25,Yes,Non-Travel,247,Research & Development,8,1,Medical,...,4,80,0,0,0,3,0,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1475,RM412,60,55+,No,Travel_Rarely,422,Research & Development,7,3,Life Sciences,...,4,80,0,33,5,1,29,8,11,10.0
1476,RM428,60,55+,No,Travel_Frequently,1499,Sales,28,3,Marketing,...,4,80,0,22,5,4,18,13,13,11.0
1477,RM537,60,55+,No,Travel_Rarely,1179,Sales,16,4,Marketing,...,4,80,0,10,1,3,2,2,2,2.0
1478,RM880,60,55+,No,Travel_Rarely,696,Sales,7,4,Marketing,...,2,80,1,12,3,3,11,7,1,9.0
1479,RM1210,60,55+,No,Travel_Rarely,370,Research & Development,1,4,Medical,...,3,80,1,19,2,4,1,0,0,0.0

In [8]:
df["Age_Category"]=df["Age"].apply(lambda x:"Young"if x <25 else "Adult"if x<=35 else "Senior")
df

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Age_Category
0,RM297,18,18-25,Yes,Travel_Rarely,230,Research & Development,3,3,Life Sciences,...,80,0,0,2,3,0,0,0,0.0,Young
1,RM302,18,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,...,80,0,0,2,3,0,0,0,0.0,Young
2,RM458,18,18-25,Yes,Travel_Frequently,1306,Sales,5,3,Marketing,...,80,0,0,3,3,0,0,0,0.0,Young
3,RM728,18,18-25,No,Non-Travel,287,Research & Development,5,2,Life Sciences,...,80,0,0,2,3,0,0,0,0.0,Young
4,RM829,18,18-25,Yes,Non-Travel,247,Research & Development,8,1,Medical,...,80,0,0,0,3,0,0,0,0.0,Young
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1475,RM412,60,55+,No,Travel_Rarely,422,Research & Development,7,3,Life Sciences,...,80,0,33,5,1,29,8,11,10.0,Senior
1476,RM428,60,55+,No,Travel_Frequently,1499,Sales,28,3,Marketing,...,80,0,22,5,4,18,13,13,11.0,Senior
1477,RM537,60,55+,No,Travel_Rarely,1179,Sales,16,4,Marketing,...,80,0,10,1,3,2,2,2,2.0,Senior
1478,RM880,60,55+,No,Travel_Rarely,696,Sales,7,4,Marketing,...,80,1,12,3,3,11,7,1,9.0,Senior
1479,RM1210,60,55+,No,Travel_Rarely,370,Research & Development,1,4,Medical,...,80,1,19,2,4,1,0,0,0.0,Senior

In [9]:
df["Travel_Status"]=df["BusinessTravel"].apply (lambda x:"Regular"if x== "Travel_Ready" else "Frequent"if x== "Travel_Frequently"else "No Travel")
df

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Age_Category,Travel_Status
0,RM297,18,18-25,Yes,Travel_Rarely,230,Research & Development,3,3,Life Sciences,...,0,0,2,3,0,0,0,0.0,Young,No Travel
1,RM302,18,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,...,0,0,2,3,0,0,0,0.0,Young,No Travel
2,RM458,18,18-25,Yes,Travel_Frequently,1306,Sales,5,3,Marketing,...,0,0,3,3,0,0,0,0.0,Young,Frequent
3,RM728,18,18-25,No,Non-Travel,287,Research & Development,5,2,Life Sciences,...,0,0,2,3,0,0,0,0.0,Young,No Travel
4,RM829,18,18-25,Yes,Non-Travel,247,Research & Development,8,1,Medical,...,0,0,0,3,0,0,0,0.0,Young,No Travel
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1475,RM412,60,55+,No,Travel_Rarely,422,Research & Development,7,3,Life Sciences,...,0,33,5,1,29,8,11,10.0,Senior,No Travel
1476,RM428,60,55+,No,Travel_Frequently,1499,Sales,28,3,Marketing,...,0,22,5,4,18,13,13,11.0,Senior,Frequent
1477,RM537,60,55+,No,Travel_Rarely,1179,Sales,16,4,Marketing,...,0,10,1,3,2,2,2,2.0,Senior,No Travel
1478,RM880,60,55+,No,Travel_Rarely,696,Sales,7,4,Marketing,...,1,12,3,3,11,7,1,9.0,Senior,No Travel
1479,RM1210,60,55+,No,Travel_Rarely,370,Research & Development,1,4,Medical,...,1,19,2,4,1,0,0,0.0,Senior,No Travel

In [10]:
df["Attrition_Status"]=df["Attrition"].apply(lambda x: "Left Company"if x=="Yes" else"Working")
df

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Age_Category,Travel_Status,Attrition_Status
0,RM297,18,18-25,Yes,Travel_Rarely,230,Research & Development,3,3,Life Sciences,...,0,2,3,0,0,0,0.0,Young,No Travel,Left Company
1,RM302,18,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,...,0,2,3,0,0,0,0.0,Young,No Travel,Working
2,RM458,18,18-25,Yes,Travel_Frequently,1306,Sales,5,3,Marketing,...,0,3,3,0,0,0,0.0,Young,Frequent,Left Company
3,RM728,18,18-25,No,Non-Travel,287,Research & Development,5,2,Life Sciences,...,0,2,3,0,0,0,0.0,Young,No Travel,Working
4,RM829,18,18-25,Yes,Non-Travel,247,Research & Development,8,1,Medical,...,0,0,3,0,0,0,0.0,Young,No Travel,Left Company
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1475,RM412,60,55+,No,Travel_Rarely,422,Research & Development,7,3,Life Sciences,...,33,5,1,29,8,11,10.0,Senior,No Travel,Working
1476,RM428,60,55+,No,Travel_Frequently,1499,Sales,28,3,Marketing,...,22,5,4,18,13,13,11.0,Senior,Frequent,Working
1477,RM537,60,55+,No,Travel_Rarely,1179,Sales,16,4,Marketing,...,10,1,3,2,2,2,2.0,Senior,No Travel,Working
1478,RM880,60,55+,No,Travel_Rarely,696,Sales,7,4,Marketing,...,12,3,3,11,7,1,9.0,Senior,No Travel,Working
1479,RM1210,60,55+,No,Travel_Rarely,370,Research & Development,1,4,Medical,...,19,2,4,1,0,0,0.0,Senior,No Travel,Working

In [14]:
df["Department"] = df["Department"].apply(lambda x: x.upper())
df

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Age_Category,Travel_Status,Attrition_Status,DailyRate_Bonus
0,RM297,18,18-25,Yes,Travel_Rarely,230,RESEARCH & DEVELOPMENT,3,3,Life Sciences,...,2,3,0,0,0,0.0,Young,No Travel,Left Company,253.0
1,RM302,18,18-25,No,Travel_Rarely,812,SALES,10,3,Medical,...,2,3,0,0,0,0.0,Young,No Travel,Working,893.2
2,RM458,18,18-25,Yes,Travel_Frequently,1306,SALES,5,3,Marketing,...,3,3,0,0,0,0.0,Young,Frequent,Left Company,1436.6
3,RM728,18,18-25,No,Non-Travel,287,RESEARCH & DEVELOPMENT,5,2,Life Sciences,...,2,3,0,0,0,0.0,Young,No Travel,Working,315.7
4,RM829,18,18-25,Yes,Non-Travel,247,RESEARCH & DEVELOPMENT,8,1,Medical,...,0,3,0,0,0,0.0,Young,No Travel,Left Company,271.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1475,RM412,60,55+,No,Travel_Rarely,422,RESEARCH & DEVELOPMENT,7,3,Life Sciences,...,5,1,29,8,11,10.0,Senior,No Travel,Working,464.2
1476,RM428,60,55+,No,Travel_Frequently,1499,SALES,28,3,Marketing,...,5,4,18,13,13,11.0,Senior,Frequent,Working,1648.9
1477,RM537,60,55+,No,Travel_Rarely,1179,SALES,16,4,Marketing,...,1,3,2,2,2,2.0,Senior,No Travel,Working,1296.9
1478,RM880,60,55+,No,Travel_Rarely,696,SALES,7,4,Marketing,...,3,3,11,7,1,9.0,Senior,No Travel,Working,765.6
1479,RM1210,60,55+,No,Travel_Rarely,370,RESEARCH & DEVELOPMENT,1,4,Medical,...,2,4,1,0,0,0.0,Senior,No Travel,Working,407.0

In [13]:
df["DailyRate_Bonus"]=df["DailyRate"]+(df["DailyRate"]*0.10)
df

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Age_Category,Travel_Status,Attrition_Status,DailyRate_Bonus
0,RM297,18,18-25,Yes,Travel_Rarely,230,RESEARCH & DEVELOPMENT,3,3,Life Sciences,...,2,3,0,0,0,0.0,Young,No Travel,Left Company,253.0
1,RM302,18,18-25,No,Travel_Rarely,812,SALES,10,3,Medical,...,2,3,0,0,0,0.0,Young,No Travel,Working,893.2
2,RM458,18,18-25,Yes,Travel_Frequently,1306,SALES,5,3,Marketing,...,3,3,0,0,0,0.0,Young,Frequent,Left Company,1436.6
3,RM728,18,18-25,No,Non-Travel,287,RESEARCH & DEVELOPMENT,5,2,Life Sciences,...,2,3,0,0,0,0.0,Young,No Travel,Working,315.7
4,RM829,18,18-25,Yes,Non-Travel,247,RESEARCH & DEVELOPMENT,8,1,Medical,...,0,3,0,0,0,0.0,Young,No Travel,Left Company,271.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1475,RM412,60,55+,No,Travel_Rarely,422,RESEARCH & DEVELOPMENT,7,3,Life Sciences,...,5,1,29,8,11,10.0,Senior,No Travel,Working,464.2
1476,RM428,60,55+,No,Travel_Frequently,1499,SALES,28,3,Marketing,...,5,4,18,13,13,11.0,Senior,Frequent,Working,1648.9
1477,RM537,60,55+,No,Travel_Rarely,1179,SALES,16,4,Marketing,...,1,3,2,2,2,2.0,Senior,No Travel,Working,1296.9
1478,RM880,60,55+,No,Travel_Rarely,696,SALES,7,4,Marketing,...,3,3,11,7,1,9.0,Senior,No Travel,Working,765.6
1479,RM1210,60,55+,No,Travel_Rarely,370,RESEARCH & DEVELOPMENT,1,4,Medical,...,2,4,1,0,0,0.0,Senior,No Travel,Working,407.0

In [15]:
df["Distance_Category"] = df["DistanceFromHome"].apply(
    lambda x: "Near" if x <= 5 else "Medium" if x <= 15 else "Far"
)
df

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Age_Category,Travel_Status,Attrition_Status,DailyRate_Bonus,Distance_Category
0,RM297,18,18-25,Yes,Travel_Rarely,230,RESEARCH & DEVELOPMENT,3,3,Life Sciences,...,3,0,0,0,0.0,Young,No Travel,Left Company,253.0,Near
1,RM302,18,18-25,No,Travel_Rarely,812,SALES,10,3,Medical,...,3,0,0,0,0.0,Young,No Travel,Working,893.2,Medium
2,RM458,18,18-25,Yes,Travel_Frequently,1306,SALES,5,3,Marketing,...,3,0,0,0,0.0,Young,Frequent,Left Company,1436.6,Near
3,RM728,18,18-25,No,Non-Travel,287,RESEARCH & DEVELOPMENT,5,2,Life Sciences,...,3,0,0,0,0.0,Young,No Travel,Working,315.7,Near
4,RM829,18,18-25,Yes,Non-Travel,247,RESEARCH & DEVELOPMENT,8,1,Medical,...,3,0,0,0,0.0,Young,No Travel,Left Company,271.7,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1475,RM412,60,55+,No,Travel_Rarely,422,RESEARCH & DEVELOPMENT,7,3,Life Sciences,...,1,29,8,11,10.0,Senior,No Travel,Working,464.2,Medium
1476,RM428,60,55+,No,Travel_Frequently,1499,SALES,28,3,Marketing,...,4,18,13,13,11.0,Senior,Frequent,Working,1648.9,Far
1477,RM537,60,55+,No,Travel_Rarely,1179,SALES,16,4,Marketing,...,3,2,2,2,2.0,Senior,No Travel,Working,1296.9,Far
1478,RM880,60,55+,No,Travel_Rarely,696,SALES,7,4,Marketing,...,3,11,7,1,9.0,Senior,No Travel,Working,765.6,Medium
1479,RM1210,60,55+,No,Travel_Rarely,370,RESEARCH & DEVELOPMENT,1,4,Medical,...,4,1,0,0,0.0,Senior,No Travel,Working,407.0,Near

In [16]:
df["Experience_Status"] = df["TotalWorkingYears"].apply(
    lambda x: "Experienced" if x >= 10 else "Fresher"
)
df

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Age_Category,Travel_Status,Attrition_Status,DailyRate_Bonus,Distance_Category,Experience_Status
0,RM297,18,18-25,Yes,Travel_Rarely,230,RESEARCH & DEVELOPMENT,3,3,Life Sciences,...,0,0,0,0.0,Young,No Travel,Left Company,253.0,Near,Fresher
1,RM302,18,18-25,No,Travel_Rarely,812,SALES,10,3,Medical,...,0,0,0,0.0,Young,No Travel,Working,893.2,Medium,Fresher
2,RM458,18,18-25,Yes,Travel_Frequently,1306,SALES,5,3,Marketing,...,0,0,0,0.0,Young,Frequent,Left Company,1436.6,Near,Fresher
3,RM728,18,18-25,No,Non-Travel,287,RESEARCH & DEVELOPMENT,5,2,Life Sciences,...,0,0,0,0.0,Young,No Travel,Working,315.7,Near,Fresher
4,RM829,18,18-25,Yes,Non-Travel,247,RESEARCH & DEVELOPMENT,8,1,Medical,...,0,0,0,0.0,Young,No Travel,Left Company,271.7,Medium,Fresher
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1475,RM412,60,55+,No,Travel_Rarely,422,RESEARCH & DEVELOPMENT,7,3,Life Sciences,...,29,8,11,10.0,Senior,No Travel,Working,464.2,Medium,Experienced
1476,RM428,60,55+,No,Travel_Frequently,1499,SALES,28,3,Marketing,...,18,13,13,11.0,Senior,Frequent,Working,1648.9,Far,Experienced
1477,RM537,60,55+,No,Travel_Rarely,1179,SALES,16,4,Marketing,...,2,2,2,2.0,Senior,No Travel,Working,1296.9,Far,Experienced
1478,RM880,60,55+,No,Travel_Rarely,696,SALES,7,4,Marketing,...,11,7,1,9.0,Senior,No Travel,Working,765.6,Medium,Experienced
1479,RM1210,60,55+,No,Travel_Rarely,370,RESEARCH & DEVELOPMENT,1,4,Medical,...,1,0,0,0.0,Senior,No Travel,Working,407.0,Near,Experienced

In [19]:
df[df["Age_Category"] == "Senior"]

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Age_Category,Travel_Status,Attrition_Status,DailyRate_Bonus,Distance_Category,Experience_Status
734,RM010,36,36-45,No,Travel_Rarely,1299,RESEARCH & DEVELOPMENT,27,3,Medical,...,7,7,7,7.0,Senior,No Travel,Working,1428.9,Far,Experienced
735,RM022,36,36-45,Yes,Travel_Rarely,1218,SALES,9,4,Life Sciences,...,5,3,0,3.0,Senior,No Travel,Left Company,1339.8,Medium,Experienced
736,RM039,36,36-45,No,Travel_Rarely,852,RESEARCH & DEVELOPMENT,5,4,Life Sciences,...,1,1,0,0.0,Senior,No Travel,Working,937.2,Near,Fresher
737,RM065,36,36-45,No,Travel_Rarely,1223,RESEARCH & DEVELOPMENT,8,3,Technical Degree,...,17,14,12,8.0,Senior,No Travel,Working,1345.3,Medium,Experienced
738,RM067,36,36-45,No,Travel_Frequently,1195,RESEARCH & DEVELOPMENT,11,3,Life Sciences,...,6,5,0,3.0,Senior,Frequent,Working,1314.5,Medium,Fresher
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1475,RM412,60,55+,No,Travel_Rarely,422,RESEARCH & DEVELOPMENT,7,3,Life Sciences,...,29,8,11,10.0,Senior,No Travel,Working,464.2,Medium,Experienced
1476,RM428,60,55+,No,Travel_Frequently,1499,SALES,28,3,Marketing,...,18,13,13,11.0,Senior,Frequent,Working,1648.9,Far,Experienced
1477,RM537,60,55+,No,Travel_Rarely,1179,SALES,16,4,Marketing,...,2,2,2,2.0,Senior,No Travel,Working,1296.9,Far,Experienced
1478,RM880,60,55+,No,Travel_Rarely,696,SALES,7,4,Marketing,...,11,7,1,9.0,Senior,No Travel,Working,765.6,Medium,Experienced
1479,RM1210,60,55+,No,Travel_Rarely,370,RESEARCH & DEVELOPMENT,1,4,Medical,...,1,0,0,0.0,Senior,No Travel,Working,407.0,Near,Experienced

In [21]:
new_emp = pd.DataFrame({
    "EmpID":["RM2000","RM2001"],
    "Age":[30,27],
    "AgeGroup":["26-35","26-35"],
    "Attrition":["No","Yes"]
})
new_emp

    EmpID  Age AgeGroup Attrition
0  RM2000   30    26-35        No
1  RM2001   27    26-35       Yes

In [23]:
df1 = pd.concat([df, new_emp], axis=0)
df1

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Age_Category,Travel_Status,Attrition_Status,DailyRate_Bonus,Distance_Category,Experience_Status
0,RM297,18,18-25,Yes,Travel_Rarely,230.0,RESEARCH & DEVELOPMENT,3.0,3.0,Life Sciences,...,0.0,0.0,0.0,0.0,Young,No Travel,Left Company,253.0,Near,Fresher
1,RM302,18,18-25,No,Travel_Rarely,812.0,SALES,10.0,3.0,Medical,...,0.0,0.0,0.0,0.0,Young,No Travel,Working,893.2,Medium,Fresher
2,RM458,18,18-25,Yes,Travel_Frequently,1306.0,SALES,5.0,3.0,Marketing,...,0.0,0.0,0.0,0.0,Young,Frequent,Left Company,1436.6,Near,Fresher
3,RM728,18,18-25,No,Non-Travel,287.0,RESEARCH & DEVELOPMENT,5.0,2.0,Life Sciences,...,0.0,0.0,0.0,0.0,Young,No Travel,Working,315.7,Near,Fresher
4,RM829,18,18-25,Yes,Non-Travel,247.0,RESEARCH & DEVELOPMENT,8.0,1.0,Medical,...,0.0,0.0,0.0,0.0,Young,No Travel,Left Company,271.7,Medium,Fresher
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1477,RM537,60,55+,No,Travel_Rarely,1179.0,SALES,16.0,4.0,Marketing,...,2.0,2.0,2.0,2.0,Senior,No Travel,Working,1296.9,Far,Experienced
1478,RM880,60,55+,No,Travel_Rarely,696.0,SALES,7.0,4.0,Marketing,...,11.0,7.0,1.0,9.0,Senior,No Travel,Working,765.6,Medium,Experienced
1479,RM1210,60,55+,No,Travel_Rarely,370.0,RESEARCH & DEVELOPMENT,1.0,4.0,Medical,...,1.0,0.0,0.0,0.0,Senior,No Travel,Working,407.0,Near,Experienced
0,RM2000,30,26-35,No,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,RM2001,27,26-35,Yes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
df2 = pd.concat([df.head(10), df.tail(10)], axis=0)
df2

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Age_Category,Travel_Status,Attrition_Status,DailyRate_Bonus,Distance_Category,Experience_Status
0,RM297,18,18-25,Yes,Travel_Rarely,230,RESEARCH & DEVELOPMENT,3,3,Life Sciences,...,0,0,0,0.0,Young,No Travel,Left Company,253.0,Near,Fresher
1,RM302,18,18-25,No,Travel_Rarely,812,SALES,10,3,Medical,...,0,0,0,0.0,Young,No Travel,Working,893.2,Medium,Fresher
2,RM458,18,18-25,Yes,Travel_Frequently,1306,SALES,5,3,Marketing,...,0,0,0,0.0,Young,Frequent,Left Company,1436.6,Near,Fresher
3,RM728,18,18-25,No,Non-Travel,287,RESEARCH & DEVELOPMENT,5,2,Life Sciences,...,0,0,0,0.0,Young,No Travel,Working,315.7,Near,Fresher
4,RM829,18,18-25,Yes,Non-Travel,247,RESEARCH & DEVELOPMENT,8,1,Medical,...,0,0,0,0.0,Young,No Travel,Left Company,271.7,Medium,Fresher
5,RM973,18,18-25,No,Non-Travel,1124,RESEARCH & DEVELOPMENT,1,3,Life Sciences,...,0,0,0,0.0,Young,No Travel,Working,1236.4,Near,Fresher
6,RM1154,18,18-25,Yes,Travel_Frequently,544,SALES,3,2,Medical,...,0,0,0,0.0,Young,Frequent,Left Company,598.4,Near,Fresher
7,RM1312,18,18-25,No,Non-Travel,1431,RESEARCH & DEVELOPMENT,14,3,Medical,...,0,0,0,0.0,Young,No Travel,Working,1574.1,Medium,Fresher
8,RM128,19,18-25,Yes,Travel_Rarely,528,SALES,22,1,Marketing,...,0,0,0,0.0,Young,No Travel,Left Company,580.8,Far,Fresher
9,RM150,19,18-25,No,Travel_Rarely,1181,RESEARCH & DEVELOPMENT,3,1,Medical,...,1,0,0,0.0,Young,No Travel,Working,1299.1,Near,Fresher
1470,RM233,59,55+,No,Travel_Rarely,818,HUMAN RESOURCES,6,2,Medical,...,2,2,2,2.0,Senior,No Travel,Working,899.8,Medium,Fresher
1471,RM744,59,55+,No,Travel_Rarely,715,RESEARCH & DEVELOPMENT,2,3,Life Sciences,...,5,3,4,3.0,Senior,No Travel,Working,786.5,Near,Experienced
1472,RM759,59,55+,No,Travel_Rarely,1089,SALES,1,2,Technical Degree,...,6,4,0,4.0,Senior,No Travel,Working,1197.9,Near,Experienced
1473,RM898,59,55+,No,Travel_Rarely,326,SALES,3,3,Life Sciences,...,6,1,0,5.0,Senior,No Travel,Working,358.6,Near,Experienced
1474,RM920,59,55+,No,Travel_Rarely,1429,RESEARCH & DEVELOPMENT,18,4,Medical,...,9,7,5,4.0,Senior,No Travel,Working,1571.9,Far,Experienced
1475,RM412,60,55+,No,Travel_Rarely,422,RESEARCH & DEVELOPMENT,7,3,Life Sciences,...,29,8,11,10.0,Senior,No Travel,Working,464.2,Medium,Experienced
1476,RM428,60,55+,No,Travel_Frequently,1499,SALES,28,3,Marketing,...,18,13,13,11.0,Senior,Frequent,Working,1648.9,Far,Experienced
1477,RM537,60,55+,No,Travel_Rarely,1179,SALES,16,4,Marketing,...,2,2,2,2.0,Senior,No Travel,Working,1296.9,Far,Experienced
1478,RM880,60,55+,No,Travel_Rarely,696,SALES,7,4,Marketing,...,11,7,1,9.0,Senior,No Travel,Working,765.6,Medium,Experienced
1479,RM1210,60,55+,No,Travel_Rarely,370,RESEARCH & DEVELOPMENT,1,4,Medical,...,1,0,0,0.0,Senior,No Travel,Working,407.0,Near,Experienced

In [25]:
df3 = pd.concat([df.head(2), new_emp], axis=1)
df3

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,Age_Category,Travel_Status,Attrition_Status,DailyRate_Bonus,Distance_Category,Experience_Status,EmpID,Age,AgeGroup,Attrition
0,RM297,18,18-25,Yes,Travel_Rarely,230,RESEARCH & DEVELOPMENT,3,3,Life Sciences,...,Young,No Travel,Left Company,253.0,Near,Fresher,RM2000,30,26-35,No
1,RM302,18,18-25,No,Travel_Rarely,812,SALES,10,3,Medical,...,Young,No Travel,Working,893.2,Medium,Fresher,RM2001,27,26-35,Yes

In [26]:
df1.reset_index(drop=True, inplace=True)
df1

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Age_Category,Travel_Status,Attrition_Status,DailyRate_Bonus,Distance_Category,Experience_Status
0,RM297,18,18-25,Yes,Travel_Rarely,230.0,RESEARCH & DEVELOPMENT,3.0,3.0,Life Sciences,...,0.0,0.0,0.0,0.0,Young,No Travel,Left Company,253.0,Near,Fresher
1,RM302,18,18-25,No,Travel_Rarely,812.0,SALES,10.0,3.0,Medical,...,0.0,0.0,0.0,0.0,Young,No Travel,Working,893.2,Medium,Fresher
2,RM458,18,18-25,Yes,Travel_Frequently,1306.0,SALES,5.0,3.0,Marketing,...,0.0,0.0,0.0,0.0,Young,Frequent,Left Company,1436.6,Near,Fresher
3,RM728,18,18-25,No,Non-Travel,287.0,RESEARCH & DEVELOPMENT,5.0,2.0,Life Sciences,...,0.0,0.0,0.0,0.0,Young,No Travel,Working,315.7,Near,Fresher
4,RM829,18,18-25,Yes,Non-Travel,247.0,RESEARCH & DEVELOPMENT,8.0,1.0,Medical,...,0.0,0.0,0.0,0.0,Young,No Travel,Left Company,271.7,Medium,Fresher
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1477,RM537,60,55+,No,Travel_Rarely,1179.0,SALES,16.0,4.0,Marketing,...,2.0,2.0,2.0,2.0,Senior,No Travel,Working,1296.9,Far,Experienced
1478,RM880,60,55+,No,Travel_Rarely,696.0,SALES,7.0,4.0,Marketing,...,11.0,7.0,1.0,9.0,Senior,No Travel,Working,765.6,Medium,Experienced
1479,RM1210,60,55+,No,Travel_Rarely,370.0,RESEARCH & DEVELOPMENT,1.0,4.0,Medical,...,1.0,0.0,0.0,0.0,Senior,No Travel,Working,407.0,Near,Experienced
1480,RM2000,30,26-35,No,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1481,RM2001,27,26-35,Yes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
df1.shape[0]

1482

In [28]:
salary = pd.DataFrame({
    "MonthlyBonus":[5000,7000,4000,8000,6000]
}, index=[0,1,2,3,4])
salary

   MonthlyBonus
0          5000
1          7000
2          4000
3          8000
4          6000

In [29]:
df4 = df.head(5).join(salary)
df4

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Age_Category,Travel_Status,Attrition_Status,DailyRate_Bonus,Distance_Category,Experience_Status,MonthlyBonus
0,RM297,18,18-25,Yes,Travel_Rarely,230,RESEARCH & DEVELOPMENT,3,3,Life Sciences,...,0,0,0.0,Young,No Travel,Left Company,253.0,Near,Fresher,5000
1,RM302,18,18-25,No,Travel_Rarely,812,SALES,10,3,Medical,...,0,0,0.0,Young,No Travel,Working,893.2,Medium,Fresher,7000
2,RM458,18,18-25,Yes,Travel_Frequently,1306,SALES,5,3,Marketing,...,0,0,0.0,Young,Frequent,Left Company,1436.6,Near,Fresher,4000
3,RM728,18,18-25,No,Non-Travel,287,RESEARCH & DEVELOPMENT,5,2,Life Sciences,...,0,0,0.0,Young,No Travel,Working,315.7,Near,Fresher,8000
4,RM829,18,18-25,Yes,Non-Travel,247,RESEARCH & DEVELOPMENT,8,1,Medical,...,0,0,0.0,Young,No Travel,Left Company,271.7,Medium,Fresher,6000

In [31]:
df5 = df.head(5).join(salary, how="left")
df5

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Age_Category,Travel_Status,Attrition_Status,DailyRate_Bonus,Distance_Category,Experience_Status,MonthlyBonus
0,RM297,18,18-25,Yes,Travel_Rarely,230,RESEARCH & DEVELOPMENT,3,3,Life Sciences,...,0,0,0.0,Young,No Travel,Left Company,253.0,Near,Fresher,5000
1,RM302,18,18-25,No,Travel_Rarely,812,SALES,10,3,Medical,...,0,0,0.0,Young,No Travel,Working,893.2,Medium,Fresher,7000
2,RM458,18,18-25,Yes,Travel_Frequently,1306,SALES,5,3,Marketing,...,0,0,0.0,Young,Frequent,Left Company,1436.6,Near,Fresher,4000
3,RM728,18,18-25,No,Non-Travel,287,RESEARCH & DEVELOPMENT,5,2,Life Sciences,...,0,0,0.0,Young,No Travel,Working,315.7,Near,Fresher,8000
4,RM829,18,18-25,Yes,Non-Travel,247,RESEARCH & DEVELOPMENT,8,1,Medical,...,0,0,0.0,Young,No Travel,Left Company,271.7,Medium,Fresher,6000

In [33]:
df4[["EmpID", "Department", "MonthlyBonus"]]

   EmpID              Department  MonthlyBonus
0  RM297  RESEARCH & DEVELOPMENT          5000
1  RM302                   SALES          7000
2  RM458                   SALES          4000
3  RM728  RESEARCH & DEVELOPMENT          8000
4  RM829  RESEARCH & DEVELOPMENT          6000

In [34]:
df4.shape[0]

5