joins

In [2]:
import pandas as pd

In [4]:
df1 = pd.DataFrame({
    "Name":["Anu","Arun","Meera"]
},index=[1,2,3])
df1

    Name
1    Anu
2   Arun
3  Meera

In [7]:
df2= pd.DataFrame({
    "Marks":[85,90,95]
},index=[1,3,2])
df2

   Marks
1     85
3     90
2     95

In [8]:
#joins DataFrame using the index
df1 = pd.DataFrame({
    "Name":["Anu","Arun","Meera"]
},index=[1,2,3])

df2= pd.DataFrame({
    "Marks":[85,90,95]
},index=[1,3,2])

print(df1.join(df2))

    Name  Marks
1    Anu     85
2   Arun     95
3  Meera     90

concat

In [12]:
df3=pd.concat([df1,df2])#default axis
df3

    Name  Marks
1    Anu    NaN
2   Arun    NaN
3  Meera    NaN
1    NaN   85.0
3    NaN   90.0
2    NaN   95.0

In [9]:
df3=pd.concat([df1,df2],axis=1)
df3

    Name  Marks
1    Anu     85
2   Arun     95
3  Meera     90

In [10]:
df3=pd.concat([df1,df3])
df3

    Name  Marks
1    Anu    NaN
2   Arun    NaN
3  Meera    NaN
1    Anu   85.0
2   Arun   95.0
3  Meera   90.0

GroupBy

In [13]:
data = {
    "Department":["HR","IT","HR","IT","Sales"],
    "Salary":[30000,50000,35000,55000,40000]
}
df=pd.DataFrame(data)
df

  Department  Salary
0         HR   30000
1         IT   50000
2         HR   35000
3         IT   55000
4      Sales   40000

In [14]:
df.groupby("Department")["Salary"].sum()

Department
HR        65000
IT       105000
Sales     40000
Name: Salary, dtype: int64

In [16]:
print(df.groupby("Department")["Salary"].agg(["sum","mean","max","min","count"]))

               sum     mean    max    min  count
Department
HR           65000  32500.0  35000  30000      2
IT          105000  52500.0  55000  50000      2
Sales        40000  40000.0  40000  40000      1

applies a function to each row or column

In [17]:
df=pd.DataFrame({
    "Marks":[80,90,95,40,39,4]})
df["Bonus"]=df["Marks"].apply(lambda x: x+5)
print(df)

   Marks  Bonus
0     80     85
1     90     95
2     95    100
3     40     45
4     39     44
5      4      9

In [18]:
def passm(x):
    if x>=40:
        return 'pass'
    else:
        return 'fail'

In [20]:
df["Result"]=df["Marks"].apply(passm)
df

   Marks  Bonus Result
0     80     85   pass
1     90     95   pass
2     95    100   pass
3     40     45   pass
4     39     44   fail
5      4      9   fail

In [21]:
df["Result"]=df["Marks"].apply(
    lambda x: "Pass" if x>=40 else "Fail"
)
df

   Marks  Bonus Result
0     80     85   Pass
1     90     95   Pass
2     95    100   Pass
3     40     45   Pass
4     39     44   Fail
5      4      9   Fail

Date and Time

In [22]:
data={'time':['2025-01-27 14:45:30','2025-02-05 09:15:00','2025-03-10 20:30:45']}
df=pd.DataFrame(data)
df

                  time
0  2025-01-27 14:45:30
1  2025-02-05 09:15:00
2  2025-03-10 20:30:45

In [23]:
df.dtypes

time    str
dtype: object

In [26]:
#convert to datetime
df['time']=pd.to_datetime(df['time'])

In [27]:
df.dtypes

time    datetime64[us]
dtype: object

In [32]:
df['year']=df['time'].dt.year

# extract month
df['month']=df['time'].dt.month

#extract  day
df['day']=df['time'].dt.day

#xtract hour
df['hour']=df['time'].dt.hour

#extract minute
df['minute']=df['time'].dt.minute

#extract second
df['second']=df['time'].dt.second

#extract day of the week
df['dayofweek']=df['time'].dt.dayofweek

#extract week number of the year
df['week']=df['time'].dt.isocalendar().week

#extract quarter
df['quarter']=df['time'].dt.quarter

#get the name of the day(eg:monday)
df['weekday']=df['time'].dt.day_name()

In [33]:
df

,time,year,month,day,hour,minute,second,dayofweek,week,quarter,weekday
0,2025-01-27 14:45:30,2025,1,27,14,45,30,0,5,1,Monday
1,2025-02-05 09:15:00,2025,2,5,9,15,0,2,6,1,Wednesday
2,2025-03-10 20:30:45,2025,3,10,20,30,45,0,11,1,Monday

Data Validation

In [4]:
#check missing values
df = pd.DataFrame({
    "Name":["Anu","Arun",None,"Anu"],
    "Marks":[85,None,90,85]
})
df

   Name  Marks
0   Anu   85.0
1  Arun    NaN
2   NaN   90.0
3   Anu   85.0

In [5]:
df.isnull()
#df.isna().sum()

    Name  Marks
0  False  False
1  False   True
2   True  False
3  False  False

In [6]:
print(df.isnull().sum())

Name     1
Marks    1
dtype: int64

In [8]:
#duplicate rows
print(df.duplicated())

0    False
1    False
2    False
3     True
dtype: bool

In [9]:
print(df.duplicated().sum())

1

In [10]:
df.drop_duplicates(inplace=True)

In [12]:
df

   Name  Marks
0   Anu   85.0
1  Arun    NaN
2   NaN   90.0

In [13]:
print(df.dtypes)

Name         str
Marks    float64
dtype: object

In [14]:
#validate Numeric Range
df = pd.DataFrame({
    "Age":[20,25,17,45]
})
print(df[df["Age"]>= 18])

   Age
0   20
1   25
3   45

Data Transformation

Data transformation converts data into a suitable format for analysis

In [16]:
#rename column
df.rename(columns={"Age":"Student_Age"},inplace =True)
print(df)

   Student_Age
0           20
1           25
2           17
3           45

In [17]:
df.Student_Age.dtypes

dtype('int64')

In [18]:
df["Student_Age"]=df["Student_Age"].astype('int32')#float
print(df.dtypes)

Student_Age    int32
dtype: object

In [19]:
#create new column
df["Age_After_5_Years"]=df["Student_Age"] +5
print(df)

   Student_Age  Age_After_5_Years
0           20                 25
1           25                 30
2           17                 22
3           45                 50

In [20]:
#replace values 
df = pd.DataFrame({
    "Gender":["M","F","M"]
})
df["Gender"]=df["Gender"].replace({
    "M":"Male",
    "F":"Female"
})
print(df)

   Gender
0    Male
1  Female
2    Male

In [21]:
#convert text to uppercase
df = pd.DataFrame({
    "Name":["Anu","Arun","Meera"]
})
df["Name1"]=df["Name"].str.upper()
print(df)

    Name  Name1
0    Anu    ANU
1   Arun   ARUN
2  Meera  MEERA

In [23]:
#convert text to  lowercase
df["Name2"]=df["Name"].str.lower()
df

    Name  Name1  Name2
0    Anu    ANU    anu
1   Arun   ARUN   arun
2  Meera  MEERA  meera

In [25]:
#remove space
df = pd.DataFrame({
    "Name":[" Anu "," Arun "," Meera "]
})
df["Name"]=df["Name"].str.strip()
df

    Name
0    Anu
1   Arun
2  Meera